### ISSUE TITLE
main branch cannot compile, please update dependency rocksdb version

### ISSUE THREAD

**Issue by hxzhao527** [datafuselabs/openraft#1071]
# Describe the bug
Code in branch main cannot be compiled.

# To Reproduce
1. `git clone git@github.com:datafuselabs/openraft.git`
2. `cargo check`

# Expected behavior
![image](https://github.com/datafuselabs/openraft/assets/8402502/fb161c80-8c37-4dbe-acf1-12f65b688382)

# Actual behavior
![image](https://github.com/datafuselabs/openraft/assets/8402502/cb30c3f4-3529-44ff-86ba-df142b5269c2)
![image](https://github.com/datafuselabs/openraft/assets/8402502/7ef282bd-ec5a-4969-813a-997e32c4db0d)

# Env (please complete the following information):
- Openraft version:  current main branch, b3c1f46ebca4cb26b2c92319a5ce0f8b88ed5d62
- Rust-toolchain: `cargo 1.78.0-nightly (f772ec022 2024-03-01)`
- OS: `Linux archlinux 6.7.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 x86_64 GNU/Linux`
- CPU: x86_64

# Additional context
1. command c++ version: `c++ (GCC) 13.2.1 20230801`

current main brach depends on `rocksdb = "0.20.1"`
https://github.com/datafuselabs/openraft/blob/b3c1f46ebca4cb26b2c92319a5ce0f8b88ed5d62/stores/rocksstore/Cargo.toml#L20-L23

the depency chain is 
```mermaid
graph LR
    A[openraft] --> B["rocksdb 0.20.1"] --> C["librocksdb-sys-0.10.0+7.9.2"] --> D["rocksdb 444b3f4"]
```
this version rocksdb c++ code leak header `#include <cinttypes>` in `util/string_util.h` fails compiling.
https://github.com/facebook/rocksdb/blob/444b3f4845dd01b0d127c4b420fdd3b50ad56682/util/string_util.h#L9-L14

# solution
just update dependency rocksdb to newer version, like `0.22.0`.

**Comment by drmingdrmer** [comment]
Thank you for reminding! Let me fix it!
