### ISSUE TITLE
Proposal: Remove `RaftLogReader` Trait Dependency from `RaftLogStorage`

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#1118]
#### Current Implementation
`RaftLogStorage<C>` is currently a subtrait of `RaftLogReader<C>`:
```rust
trait RaftLogStorage<C>: RaftLogReader<C> {}
```

#### Proposed Change
As our codebase has evolved, the main loop no longer requires reading logs from `RaftLogStorage`. Thus, I propose removing `RaftLogReader` as a dependency from the `RaftLogStorage` trait:
```rust
trait RaftLogStorage<C> {}
```

#### Rationale
This change will simplify the trait hierarchy, reduce unnecessary coupling, and better align with our current usage, where log reading in the main loop is not needed.

I appreciate any feedback on this proposal and am ready to discuss further or adjust the approach based on team input.

**Comment by schreter** [comment]
Fine for me :-).

In our codebase, we made an indirection to support log reading from both sides. This will become obsolete.
