### ISSUE TITLE
unrecognized feature for crate openraft: type-alias

### ISSUE THREAD

**Issue by GaoNeng-wWw** [datafuselabs/openraft#1139]
**Describe the bug**
can not enable `type-alias` feature

**To Reproduce**
1. `cargo add openraft -f type-alias`

**Expected behavior**
can enable 'type-alias' feature

**Actual behavior**
![image](https://github.com/datafuselabs/openraft/assets/31283122/3eff5c01-d870-4665-97d7-35bc1193926e)

**Env (please complete the following information):**
- Openraft version [v0.9.13]
- Does the bug still there in the latest version? [Yes]
- Rust-toolchain: [cargo 1.75.0 (1d8b05cdd 2023-11-20)]
- OS: [Windows 10 18362]
- CPU: [处理器	Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz，3200 Mhz]

**Comment by drmingdrmer** [comment]
There is no `type-alias` feature in 0.9 releases. It is introduced in the main branch for release 0.10

**Comment by GaoNeng-wWw** [comment]
Thanks

**Comment by GaoNeng-wWw** [comment]
> There is no `type-alias` feature in 0.9 releases. It is introduced in the main branch for release 0.10

Thanks
