### ISSUE TITLE
Update quickstart to include Responder for RaftTypeConfig

### ISSUE THREAD

**Issue by danthegoodman1** [datafuselabs/openraft#1168]
**What kind of doc do you ask for?**
- [ ] Code comments.
- [ ] Architecture design.
- [ ] Algorithm explanation.
- [x] Guide.
- [x] Examples.

**Describe the information you want**
Missing the `Responder` type for the example in https://docs.rs/openraft/latest/openraft/docs/getting_started/index.html (RaftTypeConfig).

**Comment by drmingdrmer** [comment]
The `Responder` type is optional and can be left absent. These has been added to `getting-started.md` in:
- #1181
