### ISSUE TITLE
Add test suite to ensure the correctness of `AsyncRuntime` implementation.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#1209]

**Comment by SteveLauC** [comment]
I wonder what kinds of tests we should add for an implementation of `AsyncRuntime`, for this test suite, I think we should verify the functions and primitives will work correctly. 

I also want to run some integration tests to check if Openraft would work with the runtime as well.

Thoughts on this?

**Comment by drmingdrmer** [comment]
For example for `Mutex`, it should provide exclusive accessing to some value. Such as:
https://github.com/drmingdrmer/openraft/blob/bc4b4e54661308ae47b88b39373f82c54dd5780c/openraft/src/sync/mutex.rs#L130-L168

**Comment by SteveLauC** [comment]
> At least the very basic behavior should be guaranteed by these tests.

Will give this a try this morning.

> There is also a test suite to ensure the behaviors of RaftLogStorage

Yeah, I am thinking about putting the test suite for logs and state machine in a module `log`, and adding another module `runtime` for the tests of `AsyncRuntime`.

**Comment by SteveLauC** [comment]
Looks like this can be closed as well. 😀

**Comment by drmingdrmer** [comment]
Aye!
