### ISSUE TITLE
New release to remove version pin of proc-macro2

### ISSUE THREAD

**Issue by thalesfragoso** [datafuselabs/openraft#1234]
A new version of the `quote` crate was recently released, which bumps its minimum `proc-macro2` dependency to `1.0.80`.
The latest version of `openraft-macros` strictly asks for a version `<1.0.80`, which means that `cargo update` will downgrade one or the other.

#1230 already removed that requirement, but it wasn't released yet.

**Comment by drmingdrmer** [comment]
Fixed in:
- https://github.com/datafuselabs/openraft/tree/v0.9.14

**Comment by drmingdrmer** [comment]
Thank you for reminding. Please update to v0.9.14 to fix this issue:)
