### ISSUE TITLE
Add Doc: explain send_append_entires 

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#124]
This method is a bit complicated and needs a nice explanation.

It involves: 
- binary search for the matching log id on a follower.
- loading log entries from non-snapshot storage API.
- deal with lack-entry error and switch to snapshot replication.

**Comment by YangKian** [comment]
Hi, can I claim this assignment？ I‘m studying the code, doing some output may help me check my understanding. I will try my best to finish it this week.

**Comment by drmingdrmer** [comment]
Appreciating!

**Comment by YangKian** [comment]
Thanks XD

**Comment by lichuang** [comment]
> Hi, can I claim this assignment？ I‘m studying the code, doing some output may help me check my understanding. I will try my best to finish it this week.

cool,maybe we could build the doc together like wiki.

**Comment by drmingdrmer** [comment]
> > Hi, can I claim this assignment？ I‘m studying the code, doing some output may help me check my understanding. I will try my best to finish it this week.
> 
> cool,maybe we could build the doc together like wiki.

Hmm... the wiki page sometimes runs out of date with the source code.

What about the online guide, which is always sync-ed with the `main` branch:
https://datafuselabs.github.io/openraft/

And updating the markdown in the `guide/` folder would be as easy as the wiki.

**Comment by YangKian** [comment]
> cool,maybe we could build the doc together like wiki.

Sounds interesting, I'd like to join. 

> the wiki page sometimes runs out of date with the source code.

Agreed, the online guide is more appropriate, we can update the guide directly

**Comment by YangKian** [comment]
Sorry I've been so busy lately :crying_cat_face: , I may need another 2 - 3 days to complete this task. Here I'd like to synchronize the progress, I've finished reading most of the relevant code and started to organize the documentation, there are still some areas that need further confirmation, and I also want to read some code of the relevant tests. I‘ll finish it as soon as possible.

**Comment by drmingdrmer** [comment]
> Sorry I've been so busy lately 😿 , I may need another 2 - 3 days to complete this task. Here I'd like to synchronize the progress, I've finished reading most of the relevant code and started to organize the documentation, there are still some areas that need further confirmation, and I also want to read some code of the relevant tests. I‘ll finish it as soon as possible.

That's OK man~
