### ISSUE TITLE
> And there should be well-defined what to do when a member is removed from Membership.members(): The options are: turn it to a learner, or just remove it.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#130]
> And there should be well-defined what to do when a member is removed from Membership.members(): The options are: turn it to a learner, or just remove it.

cool,maybe we can open an new issue to refactor this function.

_Originally posted by @lichuang in https://github.com/datafuselabs/openraft/issues/129#issuecomment-1016416309_

**Comment by lichuang** [comment]
https://github.com/datafuselabs/openraft/pull/148
