### ISSUE TITLE
> It seems we should add learners and change members in one log entry. Then there won't be such a problem.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#137]
> It seems we should add learners and change members in one log entry. Then there won't be such a problem.

yes,i agree with this,i will refactor the source.

> Another issue is that we need to spawn replication tasks just after append_payload_to_log() and before replicate_client_request().

ok, assign a new issue to me.

_Originally posted by @lichuang in https://github.com/datafuselabs/openraft/pull/129#discussion_r788441250_

**Comment by lichuang** [comment]
https://github.com/datafuselabs/openraft/pull/129
