### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by ppamorim** [datafuselabs/openraft#153]
Could you please add a demo for that, I am trying to follow the tutorial but it's missing a lot of information. Would be nice to have a simple demo implementation of multiple server running and applying the consensus. The content inside `Getting Started` is just a base implementation of what this library could be. For example:

What `get_id_from_storage()` could be?
How to properly implement `RaftRouter` and `RaftStorage`?

After some investigation I noticed that the demo is outdated. Could you please update it?

How I read data from `MemStore`? What are the required steps? The documentation is not clear about that.

**Comment by ppamorim** [comment]
@BohuTANG Could you please help me to understand better the project, so far I could implement that: https://github.com/ppamorim/t-pro-cognito

**Comment by BohuTANG** [comment]
I think @drmingdrmer will give some comments here later

**Comment by ppamorim** [comment]
@BohuTANG Thank you. I am more than happy to create a very consice demo for the project if you help me to understand how to read/write to the cluster.

**Comment by ppamorim** [comment]
@BohuTANG @drmingdrmer When migrating, I get this error:

![Screenshot 2022-02-01 at 17 37 21](https://user-images.githubusercontent.com/5521682/152020827-872ec256-4cc3-4b8b-9ce3-b6e96638b19d.png)

Isn't `MemStore` supposed to be transparent for `openraft`?

**Comment by drmingdrmer** [comment]
@ppamorim Thank you so much! These questions expose what is lacking in this repository.

I'm gonna answer them in some separate comments in this issue and gonna provide additional info for users in several pull-request.

> What `get_id_from_storage()` could be?

To create a raft node, an `ID` has to be assigned to the raft node instance.
Where it is stored is up to the application: make it a field of the implementation of `RaftStorage`, or store it in a standalone config file.


> How to properly implement `RaftRouter` and `RaftStorage`?

For now `RaftNetwork` is only implemented in the test `fixtures` mod. What a `RaftNetwork` does is just forwarding message to another node:
https://github.com/datafuselabs/openraft/blob/950d23b35a9c15742b4a4a0825fd81059c165130/openraft/tests/fixtures/mod.rs#L828-L881

The `memstore` is relatively a complete implementation of `RaftStorage`(but actually not a key-value store, I'm gonna fix it in another PR):
https://github.com/datafuselabs/openraft/blob/950d23b35a9c15742b4a4a0825fd81059c165130/memstore/src/lib.rs#L86-L102



> How I read data from `MemStore`? What are the required steps? The documentation is not clear about that.

I was confused too when I started to use `async-raft`. Let me make it a real key-value store in another PR.

**Comment by ppamorim** [comment]
@drmingdrmer Thank you for the lovely answer, I am more than happy to help in the implementation of the demo.

**Comment by ppamorim** [comment]
I will close this issue due being slate.
