### ISSUE TITLE
Update the demo, create a complete raft application as demo

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#155]
- Originally mentioned by @ppamorim in #153 

TODO:

- [ ] Create demo implementation of `RaftNetwork`.
- [ ] Make crate `memstore` a key-value store to precisely reflect what real-world storage is like.
- [ ] Build an example that brings up a 3-nodes raft cluster application.
- [ ] Update `getting-started.md` to show how to build this example app.

**Comment by ppamorim** [comment]
@drmingdrmer I can implement in a PR the base for the demo and we can work together on that, what about it?

**Comment by drmingdrmer** [comment]
@ppamorim 
There is still something in openraft not that clear to a user.
I'm working on a draft runnable demo cluster implementation based on your repo.

Then you could just review and help on improve it:DDD

**Comment by ppamorim** [comment]
@drmingdrmer Nice, I am really happy to see that something is being created around that. To help you better, I created this branch in my fork that you can use as inspiration: https://github.com/ppamorim/openraft/tree/feature/demo/example
It's not compiling but it will give you a idea what I am trying to do.

**Comment by drmingdrmer** [comment]
@ppamorim 
I just created a PR:
https://github.com/datafuselabs/openraft/pull/156
Hoping it explains things.
Looking forward to your advice!

Yes, the network layer is almost copied from your codes when I was building this example :DDD.

**Comment by MikaelCall** [comment]
@drmingdrmer 

I would consider adding a client implementation as well since "all communication has to go through the leader" and "it is the clients responsibility to send requests to the leader". That is, show a simple client implementation that handles `ForwardToLeader` errors.

I'm very happy that you put the demo together :heart:. I think it'll help a lot of people. In particular using HTTP endpoints instead of tonic gRPC will make it easier to follow when you're just getting started.

**Comment by drmingdrmer** [comment]
> @drmingdrmer
> 
> I would consider adding a client implementation as well since "all communication has to go through the leader" and "it is the clients responsibility to send requests to the leader". That is, show a simple client implementation that handles `ForwardToLeader` errors.
> 
> I'm very happy that you put the demo together ❤️. I think it'll help a lot of people. In particular using HTTP endpoints instead of tonic gRPC will make it easier to follow when you're just getting started.

Good point. Make it a new issue :D.
In #156 the client side is just a simple shell script with `curl`, for simplicity.
I'm gonna add a rust client implementation.

**Comment by ppamorim** [comment]
@drmingdrmer I think this issue can be closed by now. :)
