### ISSUE TITLE
Example: list-nodes could verify if the nodes are still alive 

### ISSUE THREAD

**Issue by ppamorim** [datafuselabs/openraft#178]
I wonder if we could modify that function in the example to inform if the nodes are alive and being able to receive a heartbeat. I am aware that they are kept there because this function reads the state machine and returns the vec of nodes.

**Comment by drmingdrmer** [comment]
It is piece of cake to implement this function.

But the aliveness reported by a casual node is not reliable: There is a chance the communication between the endpoint node A and B is down but the leader(maybe C) is still able to reach B.
