### ISSUE TITLE
Duplicate `rust-toolchain` and `rust-toolchain.toml` (for compatibility?)

### ISSUE THREAD

**Issue by zys864** [datafuselabs/openraft#183]
Duplicate `rust-toolchain` and `rust-toolchain.toml` in the crate. 

This crate use both of them for compatibility?

Here is the doc from [rustup book](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file)

> In these cases the toolchain can be named in the project's directory in a file called rust-toolchain.toml or rust-toolchain. If both files are present in a directory, the latter is used for backwards compatibility. The files use the [TOML](https://toml.io/) format and have the following layout:

**Comment by drmingdrmer** [comment]
There is an issue with github-action `actions-rs/toolchain`: it does not recoganize the `rust-toolchain.toml` but just `rust-toolchain`.

It seems it has been fixed. I'm gonna remove the plain text one as I confirmed it is fixed.

**Comment by drmingdrmer** [comment]
Does not work yet.
https://github.com/drmingdrmer/openraft/runs/5246849191?check_suite_focus=true

https://github.com/actions-rs/toolchain/issues/126

**Comment by zys864** [comment]
But both exist in crates, only `rust-toolchain` works according to rustup book.

> If both files are present in a directory, the latter is used for backwards compatibility
