### ISSUE TITLE
Further restrict BTreeMap for implementations where BTreeSet was present.

### ISSUE THREAD

**Issue by ppamorim** [datafuselabs/openraft#194]
I might be wrong but by doing this on the current source from the main branch is possible:

```rust
let mut nodes = BTreeSet::new();
nodes.insert(app.id);
app.raft.initialize(nodes).await
```

This was the expected setup for older versions of the crate, not it was changed to `BTreeMap`, worth restricting it further?

Thank you.

**Comment by ppamorim** [comment]
Already explained here: https://github.com/datafuselabs/openraft/pull/184

**Comment by drmingdrmer** [comment]
It can be done with either BTreeSet or BTreeMap.
With a BTreeSet, you have to manage the node information yourself. But why bother? :DDD
