### ISSUE TITLE
AppendEntriesResponse should be an enum of the returned state.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#197]
Currently `AppendEntriesResponse` is:
```rust
pub struct AppendEntriesResponse {
    pub vote: Vote,
    pub success: bool,
    pub conflict: bool,
}
```

The leader has to check if a combination of these three fields is valid. E.g. `success ==  true && conflict == true` is an invalid combination.

It's better be a enum like:
```
pub enum AppendEntriesResponse {
    Ok,
    HigherVoteSeen(Vote),
    Conflict,
}
```

**Comment by Xuanwo** [comment]
Any updates on this issue? It seems already solved by https://github.com/datafuselabs/openraft/pull/219.

cc @drmingdrmer

**Comment by drmingdrmer** [comment]
Right. I forgot to close it. Thank you, my hero!
