### ISSUE TITLE
Make serde optional

### ISSUE THREAD

**Issue by schreter** [datafuselabs/openraft#207]
Currently, all types require `serde` serialization. Many "real" systems will likely use some more advanced serialization (like Cap'n Proto, FlatBuffers, Protobufs/gRPC), which do not need this and just create a burden on the developer.

Change the structures in such a way that `serde` is optional (e.g., as an optional feature).

**Comment by drmingdrmer** [comment]
> which do not need this and create a burden on the developer.

I do not quite get it.
Can you give some more information about what the **burden** is?
Does a derived implementation of `Serialize` bring more work for a developer who does not need it?

**Comment by schreter** [comment]
> Does a derived implementation of Serialize bring more work for a developer who does not need it?

Yes. I cannot simply use `#[derive(Serialize)]` on the type, since it's fairly complex. Of course, it's possible to derive it manually, but what should it do? Probably just call `unimplemented!()`, since it's not possible to implement it properly with reasonable effort (data messages that we are persisting and communicating are rather complex, encoded via capnp IDL).

So that's why I think it would be good to have it optional. Also, that would support Rust's "pay only for what you use" philosophy :-).

Of course, this is just a proposal and doesn't have a high priority.

**Comment by drmingdrmer** [comment]
> Yes. I cannot simply use `#[derive(Serialize)]` on the type, since it's fairly complex. Of course, it's possible to derive it manually, but what should it do? Probably just call `unimplemented!()`, since it's not possible to implement it properly with reasonable effort (data messages that we are persisting and communicating are rather complex, encoded via capnp IDL).

Oh, I see! You mean the trait `AppData` that forces you to implement `Serialize`.
I thought you were talking about the concrete types that already implement `Serialize`.

**Comment by schreter** [comment]
> Oh, I see! You mean the trait AppData that forces you to implement Serialize.

Yes :-).

> I thought you were talking about the concrete types that already implement Serialize.

Well, those have to be partially updated as well, since they of course require that `AppData` implements `Serialize`.

As I wrote, this has currently low prio. I see the prio primarily in the perfect API for binding the state machine, log and runtime :-).

**Comment by drmingdrmer** [comment]
- fixed in #342
