### ISSUE TITLE
Consider remove `ReplicationCore.last_log_id`

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#215]
Panic: `thread 'tokio-runtime-worker' panicked at 'assertion failed: end >= prev_index.next_index()', /Users/ppamorim/.cargo/git/checkouts/openraft-0677bbb78cc57964/2055a23/openraft/src/replication/mod.rs:312:13
`

https://github.com/datafuselabs/openraft/blob/10dd6a1303727e957be72735ecc4b9223d36eb5e/openraft/src/replication/mod.rs#L325-L350

There might be a consistency issue that will cause this panic:
https://github.com/datafuselabs/openraft/blob/10dd6a1303727e957be72735ecc4b9223d36eb5e/openraft/src/replication/mod.rs#L325-L350

The value `self.last_log_id` will not be updated if the loop started at L325 does not quit.
Thus if there are some new logs pushed into the store, during this loop, the `self.last_log_id` is a stale value.

Here it should use `log_state.last_log_id` at L339.

_Originally posted by @drmingdrmer in https://github.com/T-Pro/t-pro-cognito/issues/24#issuecomment-1053617572_

---

Storing a state in `ReplicationCore` always has a potential consistency issue.

`ReplicationCore.last_log_id` may not reflect the actual state and should be removed if possible.

A safe approach is to always read states from the `RaftLogReader`.

**Comment by lichuang** [comment]
https://github.com/datafuselabs/openraft/pull/223
