### ISSUE TITLE
`NodeId` as a parameter, to enable using GUID or other type for NodeId

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#217]
@drmingdrmer BTW, I'm working on the `NodeId` as a parameter, so we can use GUID `NodeId`s. Almost done, I'll post the change tomorrow, after some cleanups. It's quite big, since the config has to be propagated through quite a few structures.

I just noticed, there is no separate issue for it, so I'll refer to this one.

Afterwards, the `Runtime` configuration can be started, so we can provide a deterministic test runtime.

_Originally posted by @schreter in https://github.com/datafuselabs/openraft/issues/204#issuecomment-1053700936_

**Comment by schreter** [comment]
This is addressed by #204 so I'm closing this issue now. `NodeId` can now be set to any type which implements the requested traits.
