### ISSUE TITLE
Support For Stable Rust

### ISSUE THREAD

**Issue by zicklag** [datafuselabs/openraft#241]
Is it possible for openraft to support building on stable Rust? It looks like the only nightly feature required is `backtrace`, but I'm not sure if there are dependencies that need nightly, too.

**Edit:** I just realized that it isn't `openraft` that needs the nightly feature so far, it's `anyerror`. Either way is there any interest in supporting stable Rust?

**Comment by schreter** [comment]
@zicklag We are building in general with stable Rust + a few features (GATs mainly).

To work around the limitation, set environment variable `RUSTC_BOOTSTRAP="1"` in your `.cargo/config.toml`. This will enable using features in stable Rust.

Yes, it's a workaround, but it allows us to intentionally enable a few close-to-production features for our code (and a few of them were already completed during the course of the project).

BTW, Rust's std::backtrace is anyway hopelessly slow. Maybe it should be abstracted out somehow, so a better implementation can be used instead? Then it would be possible to build openraft using stable Rust only (missing backtraces in the process, but so what). Feel free to contribute :-).

**Comment by schreter** [comment]
> We

I meant in our project *using* openraft, not the openraft itself.

**Comment by zicklag** [comment]
Oh, interesting workaround. I'll keep that in mind. Thanks!
