### ISSUE TITLE
Remove role `Learner`, use `Follower` instead.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#259]
A `learner` has nothing different from a `follower`, except that a `learner` does not need to wake up to elect if it timed out receiving the heartbeat from the leader.

The event loop for learner and follower can be merged. 

For applications that use openraft, after this change,
- a `Learner` becomes a `Follower` that is not a `member`. I.e., a follower not in `RaftCore.effective_membership.alll_members()`.
- a `Follower` becomes a `Follower` that is a `member`.

`Learner` and `Follower` can be merged because in most cases, an application does not need to distinguish between a `Learner` and a `Follower`.  What an application actually cares about is `Leader` and `non-Leader`.

Currently, the membership changing API still uses the concept `Learner`.
This is not a big deal either. `add-learner` will be replaced with `add-node`, i.e., adding a general node, without specifying whether it is a member or not.

Making sense? 

Steps:

- [x] #351
- [x] #260

**Comment by schreter** [comment]
> Making sense?

Yes :-)

**Comment by MrCroxx** [comment]
If a learner can be promoted to be a follower, how to tell the defference from the view of the leader🤔.

**Comment by MrCroxx** [comment]
And with joint consensus, learner should be treated differently, like etcd does like introduce 'next learner'.

**Comment by drmingdrmer** [comment]
@MrCroxx 

> If a learner can be promoted to be a follower, how to tell the defference from the view of the leader🤔.

If the node id of the **learner** is in `RaftCore.effective_membership.all_members()`, it is a **follower**(in etcd terminology) which can become a candidate. Otherwise, it is a **learner**(in etcd terminology).

> And with joint consensus, the learner should be treated differently, like etcd does like introduce 'next learner'.

When a **member**(nodes that can elect) is removed from the `all_members()`, there is an option(`turn_to_learner`) to specify what to do about it: to remove it or convert it to a **learner**:
https://github.com/datafuselabs/openraft/blob/efdc321dad07344360732da277f63150e5cfc4d0/openraft/src/raft.rs#L323-L327

**Comment by MrCroxx** [comment]
Looks so cool!

**Comment by lichuang** [comment]
make sense:)
