### ISSUE TITLE
Discontinuous log indices in test suite last_membership_in_log

### ISSUE THREAD

**Issue by MrCroxx** [datafuselabs/openraft#282]
In `last_membership_in_log` test of the test suite, the log indices appended to the log are discontinuous (1, 3, 4). This may cause log gap and lead some raft log storage implements panic (e.g. the impl of my master project assert if there is a gap in raft log store).

I'd like to send a small PR to fix it.

https://github.com/datafuselabs/openraft/blob/b50679dcc6eba4e44a7e2106a1919f350676eff4/openraft/src/testing/suite.rs#L141-L175

**Comment by MrCroxx** [comment]
I get the purpose, these cases represents "log > applied, read from log". But still, I think it's better to append continuous log indices. 🤔

**Comment by drmingdrmer** [comment]
Hi @MrCroxx 

It's a mistake in the `last_membership_in_log` case. Thank you!
But I am not quite sure about the other **issues** you mentioned. They are possibly mistakes too :(.

The assertion about log entries have to have continuous indexes are protected by a `defensive` layer. This optional to an application. See: https://github.com/datafuselabs/openraft/blob/b50679dcc6eba4e44a7e2106a1919f350676eff4/openraft/src/defensive.rs

Env var `RAFT_STORE_DEFENSIVE=on` will turn it on.

The tests ensures defensive-check will reject non-continuous logs are included in this test-case:

https://github.com/datafuselabs/openraft/blob/b50679dcc6eba4e44a7e2106a1919f350676eff4/openraft/src/testing/suite.rs#L1230-L1257

**Comment by MrCroxx** [comment]
In some casess, it needs the indices of appended logs are larger than applied index. Would filling gaps with blank entries be fine to fix?🤔

I'd like to do a cross-validation with my project for the rest.

**Comment by drmingdrmer** [comment]
> In some casess, it needs the indices of appended logs are larger than applied index. Would filling gaps with blank entries be fine to fix?🤔

That sounds good:D

**Comment by MrCroxx** [comment]
Close via #283 .
