### ISSUE TITLE
What surrounding infrastructure is required for a high availability openraft project?

### ISSUE THREAD

**Issue by djahandarie** [datafuselabs/openraft#285]
I'm currently trying to use openraft in a new project, and am building up the surrounding logic:

1. A client aware of all the openraft nodes, which can try cycle through nodes in the case of openraft errors, leader switches, network errors, etc.
2. A watchdog for openraft nodes that can restart them when they have fatal errored for some reason (like a StorageIOError).

Is there any other things that should be included in my project? Also I'm a little surprised there is no built-in functionality for 2 and am curious what the best way to go about it would be (is there an event I can hook on for a raft error that would let me rebuild the node?)

**Comment by drmingdrmer** [comment]
Normally if `StorageError` occur, restarting a node won't help at all.
`StorageError` means the raft protocol prerequisite that disk is stable, does not hold anymore.
Then data consistency can not guaranteed.

In such a case, one need to find another server and rebuild the damaged node
with change-membership request.

> Is there any other things that should be included in my project?

As far as I know, only storage error should be considered.

> Also I'm a little surprised there is no built-in functionality for 2 and am
> curious what the best way to go about it would be (is there an event I can
> hook on for a raft error that would let me rebuild the node?)

`openraft` shut itself down at once if an `StorageError` occur.
And the `metrics` will report such an `Fatal` error(This logic still need a mock
error test to ensure it work correctly):

https://github.com/datafuselabs/openraft/blob/51817b42bb2ccd2e421a35bed8d353e7c4a7eb7d/openraft/src/core/mod.rs#L271-L285

You application should be able to receive such an event by subscribing the
metrics with `Raft::metrics()`.

When the `Fatal` error occur, the `RaftMetrics.running_state` should be a `Err()`:

```rust
pub struct RaftMetrics<C: RaftTypeConfig> {
    pub running_state: Result<(), Fatal<C::NodeId>>,
    ...
}
```

**Comment by djahandarie** [comment]
> Normally if `StorageError` occur, restarting a node won't help at all. `StorageError` means the raft protocol prerequisite that disk is stable, does not hold anymore. Then data consistency can not guaranteed.
> 
> In such a case, one need to find another server and rebuild the damaged node with change-membership request.

Ah, I think I may be misusing the type in my code then.

My code does something a little unusual, which is to spawn another process to use essentially as the state machine. The spawned process is pure and can generate/load from a snapshot, so it works out pretty well, but I need to account for the fact the process itself could disappear for any reason (OOM killed or killed by something else).

In this case I decided to throw a `StorageIOError` if the process is no longer available during `apply_to_state_machine`, because I figured I want the node to die and get restarted, read back from the log/snapshot in this case. But maybe this is a misuse of the type? I'm curious what your recommendation would be here.

> You application should be able to receive such an event by subscribing the metrics with `Raft::metrics()`.

Awesome, I wasn't aware of this hook, this looks great for making nodes manage themselves to some degree. Thanks a bunch!

**Comment by djahandarie** [comment]
> There isn't a restartable error defined in openraft :( In your case, IMHO, what to do inside `apply_to_state_machine()` is totally up to you thus you can just define an internal error for OOM. And `apply_to_state_machine()` should be able to detect such an error and reboot the child process, instead of pushing this error to openraft. Openraft does not know how to deal with such a condition:(

Hmm, the issue is that *just* rebooting the child process isn't enough -- I need to replay my log (or load from a snapshot) in order to get the child process into the right state. I'm not sure what I'd need to do in `apply_to_state_machine()` to make that happen? Manually reading the snapshot or the log in there seems like I'd be reimplementing a bunch of openraft-layer logic. Also I think that I wouldn't want that node to be the leader while that is occurring. It's basically like I want the node to error and get restarted by a watchdog, I think. I suppose I could have something on the side which just inspects the state machine and restarts the node when it determines it has become inconsistent somehow.

**Comment by schreter** [comment]
@djahandarie Not sure if it works out of the box, but wouldn't dropping the `Raft` and subsequently recreating do just that? It should cancel any tasks and drop any in-memory structures without doing proper shutdown, so that it would appear like the node died and restarted. And, of course, your snapshot would be reinstantiated and log applied.

**Comment by drmingdrmer** [comment]
Yes, as @schreter said if the restart of the subprocess will get a non-persisted state lost, restarting the entire raft node would be a solution.

> Hmm, the issue is that _just_ rebooting the child process isn't enough -- I need to replay my log (or load from a snapshot) in order to get the child process into the right state. I'm not sure what I'd need to do in `apply_to_state_machine()` to make that happen?

`apply_to_state_machine(entries)` should apply and **persist** the input `entries`.
It should not do anything about other entries.

> It's basically like I want the node to error and get restarted by a watchdog, I think. I suppose I could have something on the side which just inspects the state machine and restarts the node when it determines it has become inconsistent somehow.

If the state-machine process crashes, `apply_to_state_machien()` could just `panic!()`, since you have a watchdog:).

**Comment by djahandarie** [comment]
Thanks for the thoughts. While `panic!()`ing in `apply_to_state_machine()` alone didn't quite work (it just caused some intermediate thread to die), I set up a channel to my main thread that allows me to send a shutdown message if I've decided something has gone wrong and the process should be shutdown, and that seems to work well.

**Comment by drmingdrmer** [comment]
> While `panic!()`ing in `apply_to_state_machine()` alone didn't quite work (it just caused some intermediate thread to die).

Oh sorry! That's my mistake :(
