### ISSUE TITLE
Is there any benchmark for openraft?

### ISSUE THREAD

**Issue by MrCroxx** [datafuselabs/openraft#317]
Hi. Thanks for your efforts to build the RAFT lib with async Rust.

Recently I'm using openraft with my master graduation project, [RunKV](https://github.com/MrCroxx/RunKV) and I found some performance issues with it. Although it's **HIGHLY** likely that the performance issue comes from my implementation, I still want to ask that, is there any benchmark or perf result for openraft?

Thanks a lot. ❤️

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/22407295/165254785-c0c2d50c-26c4-4e5f-a29d-38b86909d0ec.png">

**Comment by drmingdrmer** [comment]
There is not a formal benchmark yet.

A simple local benchmark without network involved can be found here:
https://github.com/datafuselabs/openraft/blob/21959ffce1a451b7888ffcfc9931402b58fe7d6f/openraft/tests/benchmark/bench_cluster.rs#L31-L38


With 1, 3 and 5 nodes:

```
worker: 16, n: 100000, raft_members: {0}: time: 2.78026375s, ns/op: 27802, op/ms: 35
worker: 16, n: 100000, raft_members: {0, 1, 2}: time: 3.107241791s, ns/op: 31072, op/ms: 32
worker: 16, n: 100000, raft_members: {0, 1, 2, 3, 4}: time: 3.271866208s, ns/op: 32718, op/ms: 30
```

**Comment by drmingdrmer** [comment]
The above is single-thread client test.

**Comment by MrCroxx** [comment]
Thanks for the information! I'll investigate the issue of my project. BTW, is there benchmark for databend meta service?

**Comment by drmingdrmer** [comment]
I'd recall the statistic is about several thousand per second. Three nodes on a single server single threaded
