### ISSUE TITLE
Example with persistant storage

### ISSUE THREAD

**Issue by Licenser** [datafuselabs/openraft#418]
Hi,
as during an investigation in available raft libraries for rust we came across open raft, it looks brilliant! Thank you so much for this :).

As part of that we took the example and converted it to [something that has persistent storage](https://github.com/tremor-rs/uring/tree/openraft) would there be interest in a PR  to include this as a secondary example?

**Comment by drmingdrmer** [comment]
Yeah! Man!

People have asked for a persistent storage implementation, but I haven't got time for this.

If there is another crate providing a rocksdb-based store alongside the `memstore`, it will help a lot of people.

Appreciating!

**Comment by avantgardnerio** [comment]
In this example, I see the RocksDB wal is flushed during `apply_to_state_machine()` but not `append_to_log()`. Is there a reason it isn't flushed in `append_to_log()`?

**Comment by drmingdrmer** [comment]
> In this example, I see the RocksDB wal is flushed during `apply_to_state_machine()` but not `append_to_log()`. Is there a reason it isn't flushed in `append_to_log()`?

Yes you are right.
There should be a flush immediately after every write to RaftStorage.
Let me fix it.
