### ISSUE TITLE
Remove `RaftEvent::Repilcate::entry`. Replace it with log id.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#42]
Remove `RaftEvent::Repilcate::entry`. Replace it with log id.

RaftCore does not need to send an entry, but just a log id is quite enough.
Since a ReplicationStream always reads log entries from a `RaftStorage` impl.

https://github.com/datafuselabs/openraft/blob/22c540626fc23c89447985f99b991ce711e2b50c/async-raft/src/replication/mod.rs#L533-L543

**Comment by YangKian** [comment]
Hi, can I take this assignment? I would like to try it.

**Comment by drmingdrmer** [comment]
> Hi, can I take this assignment? I would like to try it.

Of course man!

/help
