### ISSUE TITLE
Do not purge log if they are not in a snapshot.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#437]
Openraft assumes once a log entry is applied with `apply_to_state_machine()`, the result is persisted. There is no need to rebuild the state machine when a node restarts.

But some application depends on a snapshot to rebuild the state machine.

Currently, it does not wait for a `build_snapshot()` to finish before deleting applied log entries. This means there may not be an up-to-date snapshot to rebuild the state machine. To fix this, openraft has not to delete any logs that are not included in the latest snapshot.

_Originally posted by @drmingdrmer in https://github.com/datafuselabs/openraft/pull/436#discussion_r914395027_

**Comment by avantgardnerio** [comment]
> There is no need to rebuild the state machine when a node restarts.

Seems to contradict:

> some application depends on a snapshot to rebuild the state machine.

Why is the application rebuilding the state machine if it does not need to?

**Comment by drmingdrmer** [comment]
> > There is no need to rebuild the state machine when a node restarts.
> 
> Seems to contradict:
> 
> > some application depends on a snapshot to rebuild the state machine.
> 
> Why is the application rebuilding the state machine if it does not need to?

When a raft node is restarted, the state machine must restore its previous state before shutting down.
This can be accomplished in either of two ways: by persisting the state on disk before `apply_to_statemachine()` returns, or by rebuilding a state machine from the last snapshot for every time the raft node starts.

So an application has to rebuild the state machine from snapshot if it chooses not to persist data in `apply_to_statemachine()`.

**Comment by drmingdrmer** [comment]
@avantgardnerio let's discuss it in a new issue.:D
