### ISSUE TITLE
Store learners in MembershipConfig.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#44]
Store learners in MembershipConfig, so that even when leadership is transferred, the replication to **Learner**s won't stop.

**Comment by drmingdrmer** [comment]
@SGZW 
This patch would affect a lot components in the code base. 
Feel free opening a discussion sharing your idea and get help:DDD

**Comment by SGZW** [comment]
> @SGZW This patch would affect a lot components in the code base. Feel free opening a discussion sharing your idea and get help:DDD

ok, this issue has ddl? i will make a plan

**Comment by drmingdrmer** [comment]
> > @SGZW This patch would affect a lot components in the code base. Feel free opening a discussion sharing your idea and get help:DDD
> 
> ok, this issue has ddl? i will make a plan

No ddl for now 🤔...

**Comment by SGZW** [comment]
> > > @SGZW This patch would affect a lot components in the code base. Feel free opening a discussion sharing your idea and get help:DDD
> > 
> > 
> > ok, this issue has ddl? i will make a plan
> 
> No ddl for now 🤔...

thx, i will give a plan before Friday

**Comment by SGZW** [comment]
sorry for delay this, I'm busy with other things recently
