### ISSUE TITLE
`RaftNetworkFactory::connect()` should return a `Result` to indicate an error during building a network connection.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#466]
`RaftNetworkFactory::connect()` returning a `Result` would be better.

There may be misconfigured node addresses being used. In such cases, the raft has a chance to discover it early. But still, the raft can do nothing about such an error, except print an error log.

Using `Result` instead of `panic()` will keep the cluster working even when there is only a minority of misconfigured nodes.

_Originally posted by @drmingdrmer in https://github.com/datafuselabs/openraft/issues/462#issuecomment-1190969779_

**Comment by ClSlaid** [comment]
I'll first make all direct function calls suffixed with `unwrap()`. As for how to exactly deal with these `Result`s, further discussion is needed.

**Comment by drmingdrmer** [comment]
> I'll first make all direct function calls suffixed with `unwrap()`. As for how to exactly deal with these `Result`s, further discussion is needed.

It's a good start. Let's discuss it in your PR:D
