### ISSUE TITLE
RaftStorage::get_initial_state should not try to fill in any default values. Leave them None and let the caller to init them.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#50]
- `InitialState::new_initial` does nothing else than build a default value of `InitialState`. 
  There is nothing a user has to implement for `InitialState`.
  Thus just let Raft do this job. A user just returns `None` in the `RaftStorage ::get_initial_state()`.

- In addition,  what `get_initial_state` does is determined. A user does not need to customize `get_initial_state` if he has already implemented other methods in `RaftStorage`. Thus `get_initial_state` can be removed.

**Comment by eliasyaoyc** [comment]
currently, get_initial_state will call InitialState::new_initial to initialize if node is first startup.
i assumed that your wants remove InitialState::new_initial and let the user actively call, right?

**Comment by drmingdrmer** [comment]
No, I do not want users to call `InitialState:: new_initial()` at all.

- `InitialState::new_initial` does nothing else than build a default value of `InitialState`. 
  There is nothing a user has to impl for `InitialState`.
  Thus just let Raft do this job. A user just returns `None`.

- In addition,  what `get_initial_state` does is determined. A user does not need to customize `get_initial_state` if he has already implemented other methods in `RaftStorage`. Thus `get_initial_state` can be removed.

**Comment by eliasyaoyc** [comment]
Gotcha, What else needs to be done on this issue？

**Comment by drmingdrmer** [comment]
🤔  Just let `get_initial_state` returns `None` if the store is uninitialized, along with tests and doc comments updated.
