### ISSUE TITLE
Different way to generate snapshots

### ISSUE THREAD

**Issue by Gab-Menezes** [datafuselabs/openraft#507]
I was thinking about how snapshots are created by Leader and sent to the Followers.
Looking at the examples (specially rocksdb one) and how the snapshot is created and distributed, and noticed a few possible problems.
1. The snapshot itself is stored in the same DB with all the other data (the DB itself will grow in size indefinitely and can result in performance loss, since DB is not optimized for large keys/values. [here - What's the maximum key and value sizes supported?](https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ)).
2. The snapshot payload can be of any size, from a few KB to a few TB.
3. The snapshot payload is json encoded (encoding json is not the fastest thing)
4. The snapshot is sent in small pieces, so the receiver should keep the information received in memory (which can be a problem, since this payload can be huge), or write to disk and process from there (which can be slow).
5. We send each part of the payload at the time (since each step is a http request), so a huge payload can take a long time to be fully sent to the Follower.
6. If a lot of nodes join the cluster at the same time the Leader would have to transfer a gigantic amount of data.

With this in mind I thought of a different way to generate this snapshot and want any thoughts and possible problems in it.
So for this to work, we would need to split the DB in two. One with state_machine data (`last_applied_log`, `last_membership`) and the `user data` section, and other DB with the raft data itself (`logs`, `vote`, `snapshot_index`, `snapshot` and etc...).

So when a snapshot is requested instead of encoding the state_machine DB and store in the `snapshot` section of the raft DB, we could generate a [checkpoint](https://github.com/facebook/rocksdb/wiki/Checkpoints) which can be very cheap as described [here - What's the difference between a snapshot, a checkpoint and a backup?](https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ). After this we could upload this checkpoint to distributed storage system (S3, nfs file system or any other thing with fast upload and download speeds in the current ecosystem being used by the user (using the fact that upload/download will always be faster than single http requests)). After this upload we would get the download link or S3 bucket/folder and use this as the `snapshot payload` in raft DB, and this same thing as the `openraft::storage::Snapshot::snapshot` value.

So when a Follower receive a `install-snapshot` request it would be only one request with the download information (really small payload), and the install process would consist in downloading this checkpoint, changing the current state_machine DB to be the one that we just downloaded, and set the current `snapshot` value in the raft DB to be the same download information received.

With this approach we can leverage the fact that checkpoint creation is cheap, upload and download speeds (in a closed ecosystem) will always be higher than single http requests, and the Follower doesn't need to keep the payload in memory/disk waiting for another request with the other part of the payload. And the leader will not have to handle/transfer big amount of data when a lot of nodes a joining the cluster at the same time, wich can be a performance problem (it will simply point the new nodes to the right place, and wait for all of then to do the heavy work).
For this approach to work we have to increase `openraft::config::Config::install_snapshot_timeout` since the download step for big state_machines can take a few seconds to a few minutes, but it's a more clean and straight forward way of doing it.

I know this is can only be applicable to rocksdb or other stores that have similar thing as checkpoints, and depends on the user ecosystem. But what I would like to know if this is a viable way of doing snapshot building/installing or can cause any problems (because in my mind this would be way faster than traditional way for big state_machines (few TB of data)) ?

With this being said, I can think of a few potencial problems:
1. If we have a cluster with multiple nodes in it, the leader and the followers can build theirs snapshots at the same/different times, so in this solution each node would generate it's snapshot and upload to a different location (new S3 folder for example) so we can keep the snapshots generated by all nodes available when the node becomes a leader (in my opnion is cheap price to pay).
2.  If a new node enters the cluster and is brought up to date using a snapshot, this new node would point to the leader's snapshot until it generates a new snapshot by it self, but the leader can generate a new snapshot before this new node generates it's own (overwriting the existing one), so for this to work we have to keep the last two snapshots saved for each node. Because in this scenario if the leader generates a new snapshot before the new node, it self can't generate another snapshot before the new node generates one. Another solution would be after the new node finish installing the new snapshot it would generate a snapshot for it self (avoiding have to keep last two snapshots for each node) (this could be done by just coping the leader's snapshot to a new location that belongs to this node, avoiding the chekpoint generation and upload step aka emplace).

**Comment by drmingdrmer** [comment]
> 1. The snapshot itself is stored in the same DB with all the other data (the DB itself will grow in size indefinitely and can result in performance loss, since DB is not optimized for large keys/values. [here - What's the maximum key and value sizes supported?](https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ)).
> 2. The snapshot payload can be of any size, from a few KB to a few TB.
> 3. The snapshot payload is json encoded (encoding json is not the fastest thing)
> 4. The snapshot is sent in small pieces, so the receiver should keep the information received in memory (which can be a problem, since this payload can be huge), or write to disk and process from there (which can be slow).
> 5. We send each part of the payload at the time (since each step is a http request), so a huge payload can take a long time to be fully sent to the Follower.


You are right, a snapshot is not necessarily stored in rocksDB, the example is a minimal application showing what has to be done but of course, not the best way to do it. Otherwise the example will be a crate of thousands of lines of codes. :(



> 6. If a lot of nodes join the cluster at the same time the Leader would have to transfer a gigantic amount of data.

Right.


> With this in mind I thought of a different way to generate this snapshot and want any thoughts and possible problems in it. So for this to work, we would need to split the DB in two. One with state_machine data (`last_applied_log`, `last_membership`) and the `user data` section, and other DB with the raft data itself (`logs`, `vote`, `snapshot_index`, `snapshot` and etc...).

This is a reasonable classification.
Actually, a raft(or other distributed consensus algorithm) does not really need a **state machine**. State machine is just a way for an application to interpret the data.

Thus `vote`, `logs` are essential to raft.
`state_machine` is part of the application, and `snapshot` is another form of `state_machine` for transport.


> So when a snapshot is requested instead of encoding the state_machine DB and store in the `snapshot` section of the raft DB, we could generate a [checkpoint](https://github.com/facebook/rocksdb/wiki/Checkpoints) which can be very cheap as described [here - What's the difference between a snapshot, a checkpoint and a backup?](https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ). After this we could upload this checkpoint to distributed storage system (S3, nfs file system or any other thing with fast upload and download speeds in the current ecosystem being used by the user (using the fact that upload/download will always be faster than single http requests)). After this upload we would get the download link or S3 bucket/folder and use this as the `snapshot payload` in raft DB, and this same thing as the `openraft::storage::Snapshot::snapshot` value.

> So when a Follower receive a `install-snapshot` request it would be only one request with the download information (really small payload), and the install process would consist in downloading this checkpoint, changing the current state_machine DB to be the one that we just downloaded, and set the current `snapshot` value in the raft DB to be the same download information received.


This is feasible with the current openraft API.
The snapshot data can be any data: it could be a serialized list of objects in S3:
https://github.com/datafuselabs/openraft/blob/main/openraft/src/storage/mod.rs#L189

When installing a snapshot, the application just deserializes the list and downloads every chunk of the **snapshot** stored in S3, then do the actual job of replacing state-machine with snapshot.



> With this approach we can leverage the fact that checkpoint creation is cheap, upload and download speeds (in a closed ecosystem) will always be higher than single http requests, and the Follower doesn't need to keep the payload in memory/disk waiting for another request with the other part of the payload. And the leader will not have to handle/transfer big amount of data when a lot of nodes a joining the cluster at the same time, wich can be a performance problem (it will simply point the new nodes to the right place, and wait for all of then to do the heavy work). For this approach to work we have to increase `openraft::config::Config::install_snapshot_timeout` since the download step for big state_machines can take a few seconds to a few minutes, but it's a more clean and straight forward way of doing it.

Right:)


> I know this is can only be applicable to rocksdb or other stores that have similar thing as checkpoints, and depends on the user ecosystem. But what I would like to know if this is a viable way of doing snapshot building/installing or can cause any problems (because in my mind this would be way faster than traditional way for big state_machines (few TB of data)) ?

Right. Using an external shared storage service to transfer snapshots has been a preference in a cloud environment.

> With this being said, I can think of a few potencial problems:
> 
> 1. If we have a cluster with multiple nodes in it, the leader and the followers can build theirs snapshots at the same/different times, so in this solution each node would generate it's snapshot and upload to a different location (new S3 folder for example) so we can keep the snapshots generated by all nodes available when the node becomes a leader (in my opnion is cheap price to pay).

Right. snapshot objects for different nodes have to be isolated with different sub-key-space.

> 2. If a new node enters the cluster and is brought up to date using a snapshot, this new node would point to the leader's snapshot until it generates a new snapshot by it self, but the leader can generate a new snapshot before this new node generates it's own (overwriting the existing one), so for this to work we have to keep the last two snapshots saved for each node. Because in this scenario if the leader generates a new snapshot before the new node, it self can't generate another snapshot before the new node generates one. Another solution would be after the new node finish installing the new snapshot it would generate a snapshot for it self (avoiding have to keep last two snapshots for each node) (this could be done by just coping the leader's snapshot to a new location that belongs to this node, avoiding the chekpoint generation and upload step aka emplace).

I do not quite get on this. Do you mean about the temp file? IMHO, every raft-node has its own snapshot objects in S3, e.g., given a cluster of `A,B,C`.
The snapshot data for `A` could be `snap/A/1.data`, `snap/A/2.data`.
The snapshot data for `B` could be `snap/B/1.data`.
The snapshot data for `C` could be `snap/C/1.data`, `snap/C/2.data`, `snap/C/3.data`.

When leader A sends a snapshot(just two object paths: `snap/A/1.data`, `snap/A/2.data`) to follower B, B should copy these two objects into a temp folder in S3: `snap/B-temp/1.data`, `snap/B-temp/2.data`.
Then B install the snapshot and replace the folder `snap/B/` with `snap/B-temp`.


There are two issues I can see with this scenario:

- Currently installing a snapshot blocks the main task `RaftCore`, which means when installing a snapshot, nothing else can be done on a follower.
- There may have to be another script for cleaning up stale snapshot objects in S3 because a raft node may crash forever before cleaning up unused snapshot objects.

**Comment by Gab-Menezes** [comment]
What I mean by this last point is:

Imagine the following folder structure to save the snapshots `snap/<node_id>/<rocksdb_files>` and we have a cluster with nodes `1, 2` (node `1` is the leader) and want o add a new node with id `3` (this node will be built with node's `1` snapshot).

First let's imagine the scenario where the new node does not copy the files to it's own folder. So simulating this scenario we have the following folder structure: `snap/1/<rocksdb_files>`. When node `3` enters the cluster it will receive this path, download it and install it and point to this folder as his snapshot. But the current data of node's `3` snapshot is under node's `1` folder, so if node `1` generate a new snapshot before node `3` (which is possible, imagine while node `3` building it self, node `1` is receiving new logs), will be a problem. For this to work we would need another folder structure: `snap/<node_id>/<snapshot_id>/<rocksdb_files>` (that's what I meant by having the last two snapshots), so when node `1` builds a new snapshot the snapshot pointed by `3` still valid.
This is not the cleanest solution, but avoids the data copy (maybe the user can't afford this copy for some reason).

And the scenario where the coping is ok you already described really well: node `3` creates a temp foder `snap/3-temp/<rocksdb_files>` by coping node's `1` snapshot, install, rename to `snap/3/<rocksdb_files>` and point it's snapshot to this folder.

* About the installation blocking the executor: In a scenario where the installation is being done to a new node we can just put it in the balancer (allow it to receive external users requests) after it completely up to date with the cluster (so blocking is not really a problem, just wait for the new node to do it's job). And in a scenario where a node is already in the cluster but lagged behind (or any other reason the will cause a snapshot installation) we may need a way to find this node and remove it from the balancer automatically.

* About the cleaning job: Yeah you are right, we may need a separate job just for cleaning S3 and in this job we can clean the stale temp folders and the folders of nodes that already leaved the cluster.

(Ty for the help explaining everything, I'm new to raft and still learning)

**Comment by Gab-Menezes** [comment]
I was about to edit my comment but you were faster haha. 

A was going to say to leverage the fact that `Raft::add_learner()` .

And another question, the snapshot creation also blocks the `RaftCore` or is handled somewhere else (i.e I can call blocking functions in it (maybe the upload step is not async or something like that)).

And I was also going to say that if a node is so far behind that it needs a snapshot maybe is not the best ideia to expose this node to the outside world since it's data is not consistent with the rest (or at least consistent enough to be considerer ok)

**Comment by drmingdrmer** [comment]
> I was about to edit my comment but you were faster haha.

🤔 

> And another question, the snapshot creation also blocks the `RaftCore` or is handled somewhere else (i.e I can call blocking functions in it (maybe the upload step is not async or something like that)). Because if it's not this can also be a problem.

Creating will be running in a separate tokio-task. It won't block `RaftCore`.
Since creating a snapshot is a read-only operation it does not have to block anything else.
But it's still up to the implementation: the storage must support building snapshot without blocking writes, such as snapshots in rocksdb.

> And I was also going to say that if a node is so far behind that it needs a snapshot maybe is not the best ideia to expose this node to the outside world since it's data is not consistent with the rest (or at least consistent enough to be considerer ok)

Normally all read and write requests should go to the leader node unless the application tolerates inconsistent read results.
If an application reads from follower nodes, `Raft.metrics()` is a way to get information about the replication state.

**Comment by Gab-Menezes** [comment]
I think that's it, ty.

Can I close this issue ?

**Comment by drmingdrmer** [comment]
Sure my friend

**Comment by ss025** [comment]
@Gab-Menezes @drmingdrmer 

I need help understanding the following use case related to the rocksdb checkpoint. 
Consider following

1. Existing cluster -> ` A(leader) `  and   `B(Follower)`
2. Snapshot of  A  -> `A/s1/*.sst `
3. New `Node C` is added as a learner
4. `Node A` sends install snapshot with `snapshot-id = s1`
5. `Node C` starts installing `snapshot = s1 ` (let's assume it will take around 15 minutes)
6. Meanwhile `Node C` is installing snapshot s1, `Node A `created another snapshot with id `s2 ->( A/s2/*.sst)`

What would happen now?

1. Will `Node A` send another install snapshot request with `id = s2`? If yes then it can go in an infinite loop.
2. We can leverage incremental checkpoints somehow but still there is a chance for an infinite loop.

**Comment by drmingdrmer** [comment]
> @Gab-Menezes @drmingdrmer
> 
> I need help understanding the following use case related to the rocksdb checkpoint. Consider following
> 
> 1. Existing cluster -> `A(leader)`  and   `B(Follower)`
> 2. Snapshot of  A  -> `A/s1/*.sst `
> 3. New `Node C` is added as a learner
> 4. `Node A` sends install snapshot with `snapshot-id = s1`
> 5. `Node C` starts installing `snapshot = s1 ` (let's assume it will take around 15 minutes)
> 6. Meanwhile `Node C` is installing snapshot s1, `Node A `created another snapshot with id `s2 ->( A/s2/*.sst)`
> 
> What would happen now?
> 
> 1. Will `Node A` send another install snapshot request with `id = s2`? If yes then it can go in an infinite loop.

In openraft, building a snapshot does not imply the snapshot has to be replicated to followers/learners.
Even if the leader does send every snapshot, the follower won't deal with the next install-snapshot request before the current one is finished. Because all updates to the **storage** are serialized in openraft.

> 2. We can leverage incremental checkpoints somehow but still there is a chance for an infinite loop.

I hope the answer to the first question solves this one too:D.

**Comment by ss025** [comment]
> In openraft, building a snapshot does not imply the snapshot has to be replicated to followers/learners.
> Even if the leader does send every snapshot, the follower won't deal with the next install-snapshot request before the current one is finished. Because all updates to the storage are serialized in openraft.

Understood. 

Let's just say, after step 6 

7. `Node A` has purged its raft log (compaction ) and created a snapshot` s2 ->( A/s2/*.sst)`
8. Once `Node C `finishes installing a snapshot, Raft core will check the replication state of Node C ( Lagging or LineRate)
9. Since Leader can not read entries from raft log (as they are purged ), it again has to install snapshot to Node C. Is this understanding correct?

**Comment by drmingdrmer** [comment]
> Understood.
> 
> Let's just say, after step 6
> 
> 7. `Node A` has purged its raft log (compaction ) and created a snapshot` s2 ->( A/s2/*.sst)`
> 8. Once `Node C `finishes installing a snapshot, Raft core will check the replication state of Node C ( Lagging or LineRate)
> 9. Since Leader can not read entries from raft log (as they are purged ), it again has to install snapshot to Node C. Is this understanding correct?

Correct. This could happen.
These too configs are meant to solve this problem, just let the leader keep many enough logs:

https://github.com/datafuselabs/openraft/blob/956177df8f57e46240ae1abf283bdd49aa9d8b85/openraft/src/config/config.rs#L154


https://github.com/datafuselabs/openraft/blob/956177df8f57e46240ae1abf283bdd49aa9d8b85/openraft/src/config/config.rs#L128-L146

And I know that etcd-raft defines a snapshot as: `snapshot_of_state_machine` plus all logs that are not in `snapshot_of_state_machine`. This way the chances of an infinite snapshot loop are reduced, but not eliminated.

I'm afraid this problem can not be eliminated:(

**Comment by ss025** [comment]
Make sense. Thank you. Closing this discussion here.
