### ISSUE TITLE
connection is never established when `RaftNetworkFactory::connect` errors once

### ISSUE THREAD

**Issue by Licenser** [datafuselabs/openraft#525]
When `RaftNetworkFactory::connect` is called and an error is generated the node connection is going to stay dead forever putting the raft cluster in invalid state.

To repdoduce:

1) a start 3 node, see up working cluster (1: leader, 2, 3: follower)
2) stop node 1
3) new leader is elected  (2: leader, 3: flower, 1: offline)
4) node 2 tries to establish connections to other nodes
5) node 2 errors in `RaftNetworkFactory::connect` to node 1
6) bring node 1 online again
7) Node 2 will never talk to node 1 as it failed in  `RaftNetworkFactory::connect`, this leads to node 1 being kept as Candidate forever

Looking further into this:

when `Command::UpdateReplicationStreams` is called as part of the leader promotion and the node fails then we don't get a replication stream update and it's never retried.

**Comment by drmingdrmer** [comment]
Forward the discussion:
https://github.com/datafuselabs/openraft/pull/526#discussion_r949105878
