### ISSUE TITLE
Difference between implementation of MemStore in main vs release-0.7 branch

### ISSUE THREAD

**Issue by ss025** [datafuselabs/openraft#528]
I see that code looks structurally different from release 0.7 in the main branch. Raft Storage is broken into multiple traits(LogReader / storage/snapshot) in main but as only one trait in 0.7. 

What is the reason behind this? Just curious to know.

Main - https://github.com/datafuselabs/openraft/blob/main/memstore/src/lib.rs
0.7 - https://github.com/datafuselabs/openraft/blob/release-0.7/memstore/src/lib.rs

**Comment by drmingdrmer** [comment]
- About log: When writing logs, there should be only one instance globally in a program that can **write logs**. But when reading logs for replication, there are multiple instances of `ReplicationStream` that read logs. Using the same type for writing and reading(as in 0.7) makes it hard to find unintentional(concurrent writing) to `RaftStorage` implementation. Thus in the main branch, it makes the handle for writing a `&mut`, so that the single-writer principle is guaranteed at compilation time. `LogReader` and `SnapshotBuilder` are handles for read-only tasks.

- Networking changes are for a similar reason. A replication stream needs to know about only one target `node`. It does not have to be bothered with node management jobs.

**Comment by ss025** [comment]
Thanks. Few more doubts.

1. What is the reason StateMachine is behind RW lock in rock store example in main branch ?

```
#[derive(Debug)]
pub struct RocksStore {
    db: Arc<rocksdb::DB>,

    /// The Raft state machine.
    pub state_machine: RwLock<RocksStateMachine>,
}
```

2. Is the main branch stable enough to build app against it? Assuming future releases will be in line with the main branch.

**Comment by drmingdrmer** [comment]
> Thanks. Few more doubts.
> 
> 1. What is the reason StateMachine is behind RW lock in rock store example in main branch ?
> 
> ```
> #[derive(Debug)]
> pub struct RocksStore {
>     db: Arc<rocksdb::DB>,
> 
>     /// The Raft state machine.
>     pub state_machine: RwLock<RocksStateMachine>,
> }
> ```

I believe it's for simplicity only.
A production should implement atomic update with rocks-transaction API.

> 2. Is the main branch stable enough to build app against it? Assuming future releases will be in line with the main branch.

The main branch is for the 0.8 release. There won't be big API changes when 0.8 is released.
Currently, the work is mainly on refactoring internal structure to make the next step of development easier and more clear, e.g. deterministic test and re-order storage command execution for maximizing throughput.

- The features are almost complete for building an application.
- The performance isn't yet fully optimized. Currently, it's about 44,000 writes per second with a single writer.
- Unit test coverage is 88%.
- The chaos test is not yet done.

**Comment by ss025** [comment]
> I believe it's for simplicity only.
> A production should implement atomic update with rocks-transaction API.

But as you mentioned there is always a single writer which will be writing to rocksdb/logs/metadata. In that case do we need synchronization or atomicity? 

Or Let me know if I understand it correctly. 

- Since we are updating multiple meta-data fields last_applied_log_id and last membership in the state machine, both need to be updated atomically (if saving in two diff fields in rocksdb) or save both values as a single key in rocksdb.


> The performance isn't yet fully optimized. Currently, it's about 44,000 writes per second with a single writer.

1. Were these writes only client requests or include other operations as well (writing raft log entries/state machine entries)? 
2. What kind of client requests were tested along with which store (Memstore / rockstore)?

**Comment by drmingdrmer** [comment]
> But as you mentioned there is always a single writer which will be writing to rocksdb/logs/metadata. In that case do we need synchronization or atomicity?

It's required when the caller must read more than one record: e.g. `get_log_state()` returns the `last_purged_log_id` and the `last_log_id`. This lock prevents one of them from being changed after reading the other one: e.g.: 
- read `last_log_id` form rocksdb;
- RaftCore purged some log and updated `last_purged_log_id`.
- read `last_purged_log_id` from rocksdb.

Then the returned `last_purged_log_id` maybe greater than `last_log_id`.

Of course, if both reading and writing are done via rocksdb transaction API, this lock can be removed.


> Or Let me know if I understand it correctly.
> 
> * Since we are updating multiple meta-data fields last_applied_log_id and last membership in the state machine, both need to be updated atomically (if saving in two diff fields in rocksdb) or save both values as a single key in rocksdb.

Right:)


> 1. Were these writes only client requests or include other operations as well (writing raft log entries/state machine entries)?

A **write** means a client request, including appending a log on the leader, replicating this log to a majority, and committing and applying it to the leader state machine.

> 2. What kind of client requests were tested along with which store (Memstore / rockstore)?

It's a very simple workload with memstore.
You can find the benchmark test here:
https://github.com/datafuselabs/openraft/blob/aba82464b8bfbdeeab8e4ea18c818dda9a681d38/openraft/tests/benchmark/bench_cluster.rs#L42-L48

**Comment by ss025** [comment]
Thanks @drmingdrmer for clarifying. From docs looks like `log_state` and `last_applied_state` are the ones which require atomicity.  or Is there anything else ? I checked for comment `NOTE: This can be made into sync, provided all state machines will use atomic read or the like.` :-)

**Comment by drmingdrmer** [comment]
> Thanks @drmingdrmer for clarifying. From docs looks like `log_state` and `last_applied_state` are the ones which require atomicity. or Is there anything else ?

Crate `memstore` is an example of what operations require atomicity.
In the implementation of `memstore`, if two updates are protected by one lock, it requires atomicity.


> I checked for comment `NOTE: This can be made into sync, provided all state machines will use atomic read or the like.` :-)

Making these API a `sync` method requires the API contract to be updated.
E.g. `apply_to_state_machine()` does not have to be `async`, if `RaftCore` does not depend on a **durable** state-machine, i.e. when `apply_to_state_machine()` returns, data does not have to be persisted. Such a feature requires `RaftCore` to be able to rebuild the state machine when starting up.

**Comment by ss025** [comment]
Got it. 

Would it make sense to force this atomicity from the framework itself? Otherwise, the implementor has to take of care of these things which may increase the chances of error.

E.g in the framework for getting log state

```
get_log_state()  { // lib function
  acquire somelock
  get_ last_log_id() ; // expose to user (storage impl)
  get_last_purged_id(); // expose to user (storage impl)
  release somelock();
}
```

Same for last_applied_state .

**Comment by drmingdrmer** [comment]
> Got it.
> 
> Would it make sense to force this atomicity from the framework itself? Otherwise, the implementor has to take of care of these things which may increase the chances of error.
> 
> E.g in the framework for getting log state
> 
> ```
> get_log_state()  { // lib function
>   acquire somelock
>   get_ last_log_id() ; // expose to user (storage impl)
>   get_last_purged_id(); // expose to user (storage impl)
>   release somelock();
> }
> ```
> 
> Same for last_applied_state .

Right. It can be simpler, in future:)

**Comment by ss025** [comment]
Great !! 👍 

Thanks a lot for clarifying my doubts. Waiting for next release :-)
