### ISSUE TITLE
Openraft won't ensure log replication when node is a learner ?

### ISSUE THREAD

**Issue by Gab-Menezes** [datafuselabs/openraft#558]
**Describe the bug**
I'm facing the scenario where I issue `client_write` in a loop of a few heavy logs (by heavy I mean, that they have a big payload when encoded, more than 256kb), I'm doing this because transmitting such a big payload at once can be a problem.
```rust
for log in logs {
    let response = app
        .raft
        .client_write(log)
        .await;
    // do something with the response
    // std::thread::sleep(std::time::Duration::from_millis(50));
}
```
The process of applying to the state machine is quite fast since this logs were previously pre processed (this is the reason why they are heavy) to avoid write contention during the `apply_to_state_machine` fase.
The problem happens when I have a cluster with 3 nodes (1 leaders + 2 learners), the leader doesn't seems to respect the 50% commit of the cluster (I don't know if this is the expected behavior with learners, since they can't be elected it's not a real problem to have the state machine behind the leader). The leader will apply the logs to it's own state machine and not to the learners.

Print screen of the leader receiving the `add_learner` and replicating the first initial logs to them.
![image](https://user-images.githubusercontent.com/29588635/190593201-90a27252-ae45-4cc5-b625-58b9d2cf76c4.png)
Print screen of the leader applying logs to it's own state machine without replicating to learners (as you can see the leader don't even send to them)
![image](https://user-images.githubusercontent.com/29588635/190592652-a6d9993b-e976-400c-8930-4b83285f3dad.png)
I even tried to change the `heartbeat_interval` to a really high value, but it didn't help.
If I uncomment the sleep part for some reason the leader will replicate the logs to the learners.

But If I change the membership (1 leader + 2 followers or 1 leader + 1 follower + 1 leaner) the logs are replicated without a problem (I don't need to add the sleep, it just works).
![image](https://user-images.githubusercontent.com/29588635/190594243-51b76532-1a65-4736-b194-59079c73e42d.png)

I really don't know if this is the expected behavior for learners and followers

**To Reproduce**
1. Create a cluster with 1 leader + 2 learners
2. Generate a few heavy logs
3. Issue a `client_write` in loop of this logs

**Expected behavior**
The leader should replicate the logs to the learners the same way it replicates to followers

**Actual behavior**
 applicable, add screenshots to help explain your problem.

**Env (please complete the following information):**
- OS: Ubuntu 22.04 WSL
- CPU: Ryzen 5600x
- Rust-toolchain: cargo 1.65.0-nightly (6da726708 2022-08-23)
- Openraft version: Commit 347aca11c913b814bba77cfee6f9635c03b353e3

**Comment by drmingdrmer** [comment]
Yes it is as expected.

A log will be committed if and only if it is replicated to a quorum(majority) of **voters**.

A learner is a node that does not grant a vote or is counted as a quorum member.
It just receives logs from the leader. That's all.

The reason for the existence of a learner is to backup data in case a voter is down, or to catch up with logs before converting the learner to a voter.

**Comment by Gab-Menezes** [comment]
Ty for the explanation.
