### ISSUE TITLE
Correct Shutdown Procedure

### ISSUE THREAD

**Issue by fredfortier** [datafuselabs/openraft#586]
I'm shutting down individual voters like this:

1. Voter sends an app-layer Logout request to the leader
2. Leader removes the voter id: `raft.change_membership(new_voter_ids, true, true)` by demoting it to learner
3. Voter waits for confirmation: `raft.wait(None).metrics(|x| !x.membership_config.voter_ids().any(|id| id == node_id))`
4. Newly demoted learner shuts down its raft: `raft.shutdown().await`

If the voter is the leader of a single-node cluster, skip the `change_membership` entirely.

The only problem with this is I get error messages in the leader's log when shutting down the newly demoted learners, which tells me something is wrong.

```
{"timestamp":" 221.443928947s","level":"WARN","message":"error sending AppendEntries RPC to target","error":"NetworkError: HTTP status client error (412 Precondition Failed) for url (http://localhost:11002/v2/append)","target":"openraft::replication","threadId":"ThreadId(3)"}
{"timestamp":" 221.444005497s","level":"ERROR","message":"error replication to target=2","error":"NetworkError: HTTP status client error (412 Precondition Failed) for url (http://localhost:11002/v2/append)","target":"openraft::replication","threadId":"ThreadId(3)"}
```

I could fix this by changing to `raft.change_membership(new_voter_ids, true, false)`, but the voter wouldn't get the acknowledgement at step 3, except by way of the leader, which would work but take away from the controlled procedure a bit. Adding a follow-up request would introduce lines of code, and the same acknowledgement dilemma.

This feels like the right procedure except for toning down the error logging when learners don't respond. Any recommendations?

**Comment by drmingdrmer** [comment]
Hmm... it's a typical dilemma with distributed consensus protocol: either to tolerate that a receiver may not receive a message or to tolerate that a sender may block forever.

Thus the leader may give up replicating the last log to a removed voter, and an app should not rely on the removed voter receiving the last log.

To complete the first policy:
- Convert it to a learner, then expect the last log on the learner. Another step that makes this policy complete is to send **another** `change-membership` request to remove this learner(to get rid of the error in the log). Then shut down the learner.

Or use the second policy:
- Or remove the voter at the first step with `change_membership(new_voters, true, false)`. And wait for the second membership log to commit by watching the **leader's** metrics.

**Comment by drmingdrmer** [comment]
BTW, why is it necessary to wait for the replication of the second membership log to the node being removed?

As soon as the leader commits this log, that voter node can be shut down without trouble.

**Comment by fredfortier** [comment]
> BTW, why is it necessary to wait for the replication of the second membership log to the node being removed?
> 
> As soon as the leader commits this log, that voter node can be shut down without trouble.

Thanks! That's where I ended up, but it's good to have your input. The leader doesn't respond until `change_membership` returns (which I believe means the `Membership` entry was committed to the raft), so it's good enough.
