### ISSUE TITLE
Cancel Snapshot Jobs

### ISSUE THREAD

**Issue by fredfortier** [datafuselabs/openraft#596]
Is it possible to cancel a `RaftSnapshotBuilder::build_snapshot` job? In my context, it would simplify things to skip snapshots in particular conditions until the state machine steps into a different state. I simply want the job to try again until a snapshot is successfully returned. I tried returning this error: `StorageIOError::new(ErrorSubject::None, ErrorVerb::Write, e.into()).into()` from the leader, but it lead to a reelection instead of retrying. Is there an error kind that would lead to the behavior I'm looking for?

**Comment by drmingdrmer** [comment]
The building snapshot is mainly a tokio task like this:
```rust
        tokio::spawn(
            async move {
                let f = builder.build_snapshot();
                let res = Abortable::new(f, reg).await;
                match res {
                    Ok(res) => match res {
                        Ok(snapshot) => {...}
                        Err(err) => {...}
                    },
                    Err(_aborted) => {...}
                }
            }
        );

```

It is possible to make it an infinite loop in which it retries calling `build_snapshot()` until it returns an `OK`. 

Another way is to block inside `build_snapshot()` until some condition become ready, e.g.:
```rust
async fn build_snapshot() {
   while !is_ready().await {
       tokio::time::sleep(Duration::from_millis(10)).await;
   }
}
```
Does this approach address your issue?

A StorageError is a fatal error. Returning it will just shut RaftCore down at once.

Introducing another **TryAgainLater** error will move this logic out of `build_snapshot()` and simplify the implementation of `build_snapshot()`. But in this way, the user application can not notify RaftCore as soon as it becomes ready.

**Comment by fredfortier** [comment]
> The building snapshot is mainly a tokio task like this:
> 
> ```rust
>         tokio::spawn(
>             async move {
>                 let f = builder.build_snapshot();
>                 let res = Abortable::new(f, reg).await;
>                 match res {
>                     Ok(res) => match res {
>                         Ok(snapshot) => {...}
>                         Err(err) => {...}
>                     },
>                     Err(_aborted) => {...}
>                 }
>             }
>         );
> ```
> 
> It is possible to make it an infinite loop in which it retries calling `build_snapshot()` until it returns an `OK`.
> 
> Another way is to block inside `build_snapshot()` until some condition become ready, e.g.:
> 
> ```rust
> async fn build_snapshot() {
>    while !is_ready().await {
>        tokio::time::sleep(Duration::from_millis(10)).await;
>    }
> }
> ```
> 
> Does this approach address your issue?
> 
> A StorageError is a fatal error. Returning it will just shut RaftCore down at once.
> 
> Introducing another **TryAgainLater** error will move this logic out of `build_snapshot()` and simplify the implementation of `build_snapshot()`. But in this way, the user application can not notify RaftCore as soon as it becomes ready.

This for the great explanation and guidance! My initial fear is that such solution would cause tasks to accumulate. With additional clarity from your guidance, it now feels like the obvious solution. We already wait for state machine backup jobs to complete in the `build_snapshot()` future, so this solution fits perfectly.

**Comment by fredfortier** [comment]
> The building snapshot is mainly a tokio task like this:
> 
> ```rust
>         tokio::spawn(
>             async move {
>                 let f = builder.build_snapshot();
>                 let res = Abortable::new(f, reg).await;
>                 match res {
>                     Ok(res) => match res {
>                         Ok(snapshot) => {...}
>                         Err(err) => {...}
>                     },
>                     Err(_aborted) => {...}
>                 }
>             }
>         );
> ```
> 
> It is possible to make it an infinite loop in which it retries calling `build_snapshot()` until it returns an `OK`.
> 
> Another way is to block inside `build_snapshot()` until some condition become ready, e.g.:
> 
> ```rust
> async fn build_snapshot() {
>    while !is_ready().await {
>        tokio::time::sleep(Duration::from_millis(10)).await;
>    }
> }
> ```
> 
> Does this approach address your issue?
> 
> A StorageError is a fatal error. Returning it will just shut RaftCore down at once.
> 
> Introducing another **TryAgainLater** error will move this logic out of `build_snapshot()` and simplify the implementation of `build_snapshot()`. But in this way, the user application can not notify RaftCore as soon as it becomes ready.

I've implemented this approach. Each build snapshot awaits some state machine conditions to be satisfied, which means the `build_snapshot` future may be long running, which seems appropriate given that it's a batch job. This approach seemed to work okay. However, when I rebased to 1235ee40 , it seems like the Raft replicator stops appending entries when `build_snapshot` starts. 

I haven't fully investigated the issue, there may be an external cause. I wanted to whether something about the concurrency model changed recently that could explain this behavior.

Here's some context, `build_snapshot` is invoked:
```
{"message":"close","time.busy":"312µs","time.idle":"6.85µs","target":"openraft::core::raft_core","span":{"name":"report_metrics"},"threadId":"ThreadId(5)"}
{"message":"close","time.busy":"399µs","time.idle":"8.31µs","target":"openraft::core::raft_core","span":{"name":"flush_metrics"},"threadId":"ThreadId(5)"}
{"message":"call_core receives result is error: false","target":"openraft::raft","span":{"name":"call_core"},"threadId":"ThreadId(5)"}
{"message":"close","time.busy":"79.0µs","time.idle":"7.27ms","target":"openraft::raft","span":{"name":"call_core"},"threadId":"ThreadId(5)"}
{"message":"close","time.busy":"155µs","time.idle":"7.27ms","target":"openraft::raft","span":{"name":"client_write"},"threadId":"ThreadId(5)"}
{"message":"Waiting for next backup","target":"ddx_core::raft::store::store_impl","span":{"name":"do_build_snapshot"},"threadId":"ThreadId(5)"}
```

Then no more requests are being added to the state machine, these lines seem to repeating for a while:
```
{"message":"close","time.busy":"6.41ms","time.idle":"9.44µs","target":"ddx_core::processor","span":{"request_index":"1004","success":"true","summary":"Block(542)","name":"exec"},"threadId":"ThreadId(1)"}
{"message":"Tick sent: 8997","target":"openraft::core::tick","span":{"name":"tick"},"threadId":"ThreadId(5)"}
{"message":"recv from rx_notify: Tick 8997","target":"openraft::core::raft_core","span":{"id":"0","state":"Leader","name":"handle_notify"},"threadId":"ThreadId(5)"}
{"message":"update_now: Instant { tv_sec: 1207261, tv_nsec: 717667949 }","target":"openraft::engine::time_state","span":{"id":"0","state":"Leader","name":"handle_notify"},"threadId":"ThreadId(5)"}
{"message":"received tick: 8997, now: Instant { tv_sec: 1207261, tv_nsec: 717667949 }","target":"openraft::core::raft_core","span":{"id":"0","state":"Leader","name":"handle_notify"},"threadId":"ThreadId(5)"}
{"message":"try to trigger election by tick, now: Instant { tv_sec: 1207261, tv_nsec: 717667949 }","target":"openraft::core::raft_core","span":{"name":"handle_tick_election"},"threadId":"ThreadId(5)"}
{"message":"already a leader, do not elect again","target":"openraft::core::raft_core","span":{"name":"handle_tick_election"},"threadId":"ThreadId(5)"}
{"message":"close","time.busy":"77.6µs","time.idle":"9.12µs","target":"openraft::core::raft_core","span":{"name":"handle_tick_election"},"threadId":"ThreadId(5)"}
{"message":"send_heartbeat","now":"Instant { tv_sec: 1207261, tv_nsec: 717667949 }","target":"openraft::core::raft_core","span":{"id":"0","name":"send_heartbeat"},"threadId":"ThreadId(5)"}
{"message":"this node is a leader","target":"openraft::engine::engine_impl","span":{"name":"get_leader_handler_or_reject"},"threadId":"ThreadId(5)"}
{"message":"close","time.busy":"50.1µs","time.idle":"10.6µs","target":"openraft::engine::engine_impl","span":{"name":"get_leader_handler_or_reject"},"threadId":"ThreadId(5)"}
{"message":"send_to_all","progress":"VecProgress { quorum_set: Joint { data: [[0]], _p: PhantomData<(u64, alloc::vec::Vec<u64>)> }, granted: Some(LogId { leader_id: LeaderId { term: 1, node_id: 0 }, index: 999 }), voter_count: 1, vector: [(0, ProgressEntry { matching: Some(LogId { leader_id: LeaderId { term: 1, node_id: 0 }, index: 999 }), curr_inflight_id: 0, inflight: None, searching_end: 1000 })], stat: Stat { update_count: 1000, move_count: 1000, is_quorum_count: 1000 } }","target":"openraft::engine::handler::replication_handler","span":{"name":"initiate_replication"},"threadId":"ThreadId(5)"}
{"message":"close","time.busy":"89.2µs","time.idle":"5.50µs","target":"openraft::engine::handler::replication_handler","span":{"name":"initiate_replication"},"threadId":"ThreadId(5)"}
{"message":"close","time.busy":"148µs","time.idle":"5.92µs","target":"openraft::engine::handler::leader_handler","span":{"name":"send_heartbeat"},"threadId":"ThreadId(5)"}
{"message":"tick triggered sending heartbeat","target":"openraft::core::raft_core","span":{"id":"0","name":"send_heartbeat"},"threadId":"ThreadId(5)"}
{"message":"close","time.busy":"411µs","time.idle":"7.48µs","target":"openraft::core::raft_core","span":{"id":"0","name":"send_heartbeat"},"threadId":"ThreadId(5)"}
{"message":"leader_step_down: node_id:0","target":"openraft::engine::engine_impl","span":{"name":"leader_step_down"},"threadId":"ThreadId(5)"}
```

**Comment by drmingdrmer** [comment]
@fredfortier let me see what's going on there 🤔

**Comment by drmingdrmer** [comment]
@fredfortier
To parallel appending-log IO and applying-log IO, applying log entries has been moved from `RaftCore` task to a separate task `sm::Worker`, and this worker handles all state-machine IO serialized, including building snapshot. Thus building a snapshot will block applying logs. There is a pending TODO that will fix your issue:

https://github.com/datafuselabs/openraft/blob/80b3c71eab649dff30de89226db07f0b4cc2bfaf/openraft/src/core/sm/mod.rs#L223-L234

I have been careless in introducing this breaking behavior change :(

Let me get this TODO done!

**Comment by fredfortier** [comment]
Thanks for the quick turnaround. I understand the root cause as explained. I'll update and re-validate now.

**Comment by drmingdrmer** [comment]
@fredfortier Let's continue further discussing in this issue:
- #823

**Comment by fredfortier** [comment]
Regarding this specific issue, your task spawning fixed the issue, but there seem to be multiple tasks spawning while the `build_snapshot` future is pending.

```
operator-node0_1  | {"timestamp":"2023-05-04T03:58:08.533751024Z","level":"INFO","message":"openraft::engine::handler::snapshot_handler::SnapshotHandler<_>::trigger_snapshot","target":"openraft::engine::handler::snapshot_handler","span":{"name":"init_raft"},"threadId":"ThreadId(3)"}
operator-node0_1  | {"timestamp":"2023-05-04T03:58:09.515947695Z","level":"INFO","message":"openraft::engine::handler::snapshot_handler::SnapshotHandler<_>::trigger_snapshot","target":"openraft::engine::handler::snapshot_handler","span":{"name":"init_raft"},"threadId":"ThreadId(5)"}
operator-node0_1  | {"timestamp":"2023-05-04T03:58:10.509952677Z","level":"INFO","message":"openraft::engine::handler::snapshot_handler::SnapshotHandler<_>::trigger_snapshot","target":"openraft::engine::handler::snapshot_handler","span":{"name":"init_raft"},"threadId":"ThreadId(5)"}
operator-node0_1  | {"timestamp":"2023-05-04T03:58:11.511494902Z","level":"INFO","message":"openraft::engine::handler::snapshot_handler::SnapshotHandler<_>::trigger_snapshot","target":"openraft::engine::handler::snapshot_handler","span":{"name":"init_raft"},"threadId":"ThreadId(3)"}
operator-node0_1  | {"timestamp":"2023-05-04T03:58:12.444429614Z","level":"INFO","message":"openraft::engine::handler::snapshot_handler::SnapshotHandler<_>::trigger_snapshot","target":"openraft::engine::handler::snapshot_handler","span":{"name":"init_raft"},"threadId":"ThreadId(4)"}
```

I assume it's multiple tasks because of the different thread numbers (unless it referring to the job that prints these messages).

**Comment by fredfortier** [comment]
There is a new issue now. Basically, in our test cluster, we always start the leader, let it do one snapshot and then start the other nodes. Taking the first snapshot works perfectly. The followers that join can install it and catchup, everything looks good. However, on the second `build_snapshot`, the leader build its snapshot successfully, but this happens to the followers:

```
{"timestamp":"2023-05-04T04:28:51.522311752Z","level":"INFO","message":"close","time.busy":"7.97ms","time.idle":"14.2µs","target":"ddx_core::processor","span":{"proof_size":"548 B","request_index":"4711","state_root_hash":"0x1d5455c56363b6cea131ff172ff64bd63bd0f39ba893d6c8c092e2219bba6f93","summary":"AdvanceEpoch(13)","tx_root_hash":"0xb8bf9678fee871402cf5e7711aff8881226db060e871931d49db66b0b51b3176","txs_len":"1","name":"ecall_finalize"},"threadId":"ThreadId(1)"}
{"timestamp":"2023-05-04T04:28:51.522442507Z","level":"INFO","message":"close","time.busy":"43.6ms","time.idle":"8.23ms","target":"ddx_core::processor","span":{"request_index":"4711","state_root_hash":"0x6348c8ae4fe497c8e82459d6fd0c1834a1751f233c947c4c307cfedc11e7506c","summary":"AdvanceEpoch(13)","tx_root_hash":"0x18be230e6706ec99d8eb2dde04486182534038b72693ecb576e08b4cc6b10e74","name":"commit"},"threadId":"ThreadId(1)"}
{"timestamp":"2023-05-04T04:28:51.522542113Z","level":"INFO","message":"close","time.busy":"4.53µs","time.idle":"56.3ms","target":"ddx_core::processor","span":{"request_index":"4711","summary":"AdvanceEpoch(13)","name":"pre_process"},"threadId":"ThreadId(1)"}
{"timestamp":"2023-05-04T04:28:51.522597407Z","level":"INFO","message":"close","time.busy":"56.4ms","time.idle":"7.80µs","target":"ddx_core::processor","span":{"request_index":"4711","success":"true","summary":"AdvanceEpoch(13)","name":"exec"},"threadId":"ThreadId(1)"}
{"timestamp":"2023-05-04T04:28:51.698259187Z","level":"INFO","message":"Exited","status":"ExitStatus(unix_wait_status(0))","target":"ddx_core::db::admin","span":{"file_path":"\"/var/local/ddx/dumps/node1/epoch-12.dump\"","pid":"Some(80)","name":"do_pg_dump"},"threadId":"ThreadId(2)"}
{"timestamp":"2023-05-04T04:28:51.698505508Z","level":"INFO","message":"close","time.busy":"637µs","time.idle":"209ms","target":"ddx_core::db::admin","span":{"file_path":"\"/var/local/ddx/dumps/node1/epoch-12.dump\"","pid":"Some(80)","name":"do_pg_dump"},"threadId":"ThreadId(2)"}
{"timestamp":"2023-05-04T04:28:51.762357377Z","level":"INFO","message":"Finished; notifying the caller","epoch_id":"12","request_index":"4711","status":"Ok(())","target":"ddx_core::snapshot::backup_mgr","span":{"service_name":"DbBackupManager","name":"spawn"},"threadId":"ThreadId(4)"}
{"timestamp":"2023-05-04T04:28:51.762529001Z","level":"INFO","message":"Backup ready","is_ok":"true","checkpoint_epoch_id":"12","request_index":"4711","target":"ddx_core::raft::store::store_impl","span":{"name":"do_build_snapshot"},"threadId":"ThreadId(4)"}
{"timestamp":"2023-05-04T04:28:51.76525002Z","level":"INFO","message":"close","time.busy":"764µs","time.idle":"1.85ms","target":"ddx_core::raft::store::store_impl","span":{"checkpoint_epoch_id":"12","node_id":"1","request_index":"4711","name":"try_build_snapshot"},"threadId":"ThreadId(4)"}
{"timestamp":"2023-05-04T04:28:51.765329814Z","level":"INFO","message":"close","time.busy":"1.64ms","time.idle":"233s","target":"ddx_core::raft::store::store_impl","span":{"name":"do_build_snapshot"},"threadId":"ThreadId(4)"}
{"timestamp":"2023-05-04T04:28:51.76547441Z","level":"INFO","message":"update the metrics for shutdown","target":"openraft::core::raft_core","span":{"name":"init_raft"},"threadId":"ThreadId(4)"}
-> {"timestamp":"2023-05-04T04:28:51.765518799Z","level":"ERROR","message":"quit RaftCore::main on error","err":"StorageError(IO { source: StorageIOError { subject: Snapshot(None), verb: Write, source: No applied entry found this cluster, backtrace: None } })","target":"openraft::core::raft_core","span":{"name":"init_raft"},"threadId":"ThreadId(4)"}
{"timestamp":"2023-05-04T04:28:51.766162693Z","level":"INFO","message":"close","time.busy":"5.22s","time.idle":"1787s","target":"ddx_core","span":{"name":"init_raft"},"threadId":"ThreadId(4)"}
{"timestamp":"2023-05-04T04:28:51.766239462Z","level":"INFO","message":"openraft::core::sm::Worker<_, _>::worker_loop: rx closed, state machine worker quit","target":"openraft::core::sm","threadId":"ThreadId(4)"}
{"timestamp":"2023-05-04T04:28:51.773813901Z","level":"INFO","message":"RaftCore exited","res":"Ok(Err(StorageError(IO { source: StorageIOError { subject: Snapshot(None), verb: Write, source: No applied entry found this cluster, backtrace: None } })))","target":"openraft::raft","threadId":"ThreadId(3)"}
{"timestamp":"2023-05-04T04:28:51.773908089Z","level":"ERROR","message":"failure sending tx to RaftCore; message: ","core_result":"Err(StorageError(IO { source: StorageIOError { subject: Snapshot(None), verb: Write, source: No applied entry found this cluster, backtrace: None } }))","target":"openraft::raft","threadId":"ThreadId(3)"}
{"timestamp":"2023-05-04T04:28:51.81351548Z","level":"INFO","message":"Tick fails to send, receiving end quit: channel closed","target":"openraft::core::tick","threadId":"ThreadId(4)"}
{"timestamp":"2023-05-04T04:28:51.850296757Z","level":"ERROR","message":"failure sending tx to RaftCore; message: ","core_result":"Err(StorageError(IO { source: StorageIOError { subject: Snapshot(None), verb: Write, source: No applied entry found this cluster, backtrace: None } }))","target":"openraft::raft","threadId":"ThreadId(4)"}
```

Note the error `Write, source: No applied entry found this cluster`. I haven't investigated this yet. I don't have openraft debug logs turned on here. Our implementation has not changed other than upgrading openraft. It's possible we forget to account for some side-effect. Please let me know if this error rights a bell. It'll be a quicker fix if I know where to look.

**Comment by drmingdrmer** [comment]
Hmm. This info level log is inappropriate. It should be debug level.

In the function `trigger_snapshot` it will just return because there is an snapshot building task ongoing.
If it does triggered a building task, it will print another info log at line 37:

https://github.com/datafuselabs/openraft/blob/7ce38e40129357ad1fa9cfa17ecd11e62361281c/openraft/src/engine/handler/snapshot_handler/mod.rs#L28-L43

**Comment by Jason5Lee** [comment]
> Another way is to block inside `build_snapshot()` until some condition become ready, e.g.:
> 
> async fn build_snapshot() {
>    while !is_ready().await {
>        tokio::time::sleep(Duration::from_millis(10)).await;
>    }
> }
> Does this approach address your issue?
> 
> A StorageError is a fatal error. Returning it will just shut RaftCore down at once.
> 
> Introducing another **TryAgainLater** error will move this logic out of `build_snapshot()` and simplify the implementation of `build_snapshot()`. But in this way, the user application can not notify RaftCore as soon as it becomes ready.

I think this works in my.requirements.

**Comment by drmingdrmer** [comment]
You can just disable auto snapshot with [SnapshotPolicy::Never](https://docs.rs/openraft/latest/openraft/enum.SnapshotPolicy.html#variant.Never)

and trigger snapshot in your application with:
[Raft::trigger](https://docs.rs/openraft/latest/openraft/raft/struct.Raft.html#method.trigger)
[Trigger::snapshot](https://docs.rs/openraft/latest/openraft/raft/trigger/struct.Trigger.html#method.snapshot)

Does this approach meet your need?

> By ensuring we only purge logs that are synced to all nodes (or not purging logs at all) 

This just reduce the availability of the cluster. This means the cluster does not tolerate any node failure, IMHO.

**Comment by drmingdrmer** [comment]
> Is it still possible that a snapshot is triggered non-manually under a never-snapshot policy (e.g., adding a learner, which shouldn’t occur during peak hours, but any other actions)?

No, replication does not trigger building a snapshot. Never just means never here :)
