### ISSUE TITLE
`RaftStorage`: add method `get_log_state() -> Result<(Option<LogId>, Option<LogId>, StorageError>` to return the first and last log id in the store

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#61]
`RaftStorage`: add method `get_log_state() -> Result<(Option<LogId>, Option<LogId>, StorageError>` to return the first and last log id in the store.

Then remove `first_id_in_log()` and `last_id_in_log()`.

This way to simplify the trait API users need to impl.

https://github.com/datafuselabs/openraft/blob/9b00e7c76c93356211be62c054c5aa20af7fe1d3/openraft/src/storage.rs#L173-L180

**Comment by drmingdrmer** [comment]
There are some corner cases with using LogId for `last_log_id.`
E.g., when there is no log at all, using `LogId`, it returns `(0,0)`, which will confuse the caller.

- `unwrap()` everywhere, for now, is not a big deal. As soon as the main branch merges #49 , it will work smoothly altogether.

**Comment by YangKian** [comment]
get~ thanks XD

**Comment by Veeupup** [comment]
@YangKian hi, this issue may have a strong connection with #49 , it seems difficult to finish each one alone, so do you want to combine these two issues into one pr to fix them or any other advice?

**Comment by YangKian** [comment]
@Veeupup Sorry for the late reply. Is it blocking something on your side? It seems to be working fine on my side, at least the tests passed after the changes were made,  if I'm not missing something. I'll fill the pr later, and if my side is blocking your progress, it's ok to leave it to me XD

**Comment by Veeupup** [comment]
@YangKian  yeah, u can finish it later. from my side, it will make nonsense if `last_id_in_log()` and some function return `LogId` ranther than `Option<LogId>`.

**Comment by YangKian** [comment]
@Veeupup Ok, let me handle it~
