### ISSUE TITLE
flush after write in rocksdb example

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#618]
> In this example, I see the RocksDB wal is flushed during `apply_to_state_machine()` but not `append_to_log()`. Is there a reason it isn't flushed in `append_to_log()`?

Yes you are right.
There should be a flush immediately after every write to RaftStorage.
Let me fix it.

_Originally posted by @drmingdrmer in https://github.com/datafuselabs/openraft/issues/418#issuecomment-1356956541_

**Comment by avantgardnerio** [comment]
Thanks!
