### ISSUE TITLE
Question: There is no need to rebuild the state machine when a node restarts.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#620]
> > There is no need to rebuild the state machine when a node restarts.
> 
> Seems to contradict:
> 
> > some application depends on a snapshot to rebuild the state machine.
> 
> Why is the application rebuilding the state machine if it does not need to?

When a raft node is restarted, the state machine must restore its previous state before shutting down.
This can be accomplished in either of two ways: by persisting the state on disk before `apply_to_statemachine()` returns, or by rebuilding a state machine from the last snapshot for every time the raft node starts.

So an application has to rebuild the state machine from snapshot if it chooses not to persist data in `apply_to_statemachine()`.

_Originally posted by @drmingdrmer in https://github.com/datafuselabs/openraft/issues/437#issuecomment-1357044036_

**Comment by avantgardnerio** [comment]
Thank you for this clarification!
