### ISSUE TITLE
What's blocking openraft from using stable rust?

### ISSUE THREAD

**Issue by TheWaWaR** [datafuselabs/openraft#666]
I noticed that with `cargo build` is ok with stable rust 1.65, then what's blocking openraft from using stable rust?

**Comment by drmingdrmer** [comment]
Nothing blocks it. 

But openraft depends on some features to build error backtrace. If you want to enable backtrace, you have to use nightly or use stable with env variable 'RUSTC_BOOTSTRAP="1"':
```
#![cfg_attr(feature = "bt", feature(error_generic_member_access))]
#![cfg_attr(feature = "bt", feature(provide_any))]
#![cfg_attr(feature = "bench", feature(test))]
```

**Comment by TheWaWaR** [comment]
Thanks.
