### ISSUE TITLE
questions on the process of log sync to followers from leader

### ISSUE THREAD

**Issue by foonsun** [datafuselabs/openraft#690]
**What kind of doc do you ask for?**
- Architecture design.

**Describe the information you want**
A clear and concise description of what you want.

"在一个 Raft 集群中，只有 Leader 节点能够处理客户端的请求（如果客户端的请求发到了 Follower，Follower 将会把请求重定向到 Leader），客户端的每一个请求都包含一条被复制状态机执行的指令。Leader 把这条指令作为一条新的日志条目（Entry）附加到日志中去，然后并行得将附加条目发送给 Followers，让它们复制这条日志条目。

当这条日志条目被 Followers 安全复制，Leader 会将这条日志条目应用到它的状态机中，然后把执行的结果返回给客户端。如果 Follower 崩溃或者运行缓慢，再或者网络丢包，Leader 会不断得重复尝试附加日志条目（尽管已经回复了客户端）直到所有的 Follower 都最终存储了所有的日志条目，确保强一致性。"

想咨询的是: openraft实现的raft集群中，leader收到请求后，是否会将日志同步给followers，收到followers的response后（也就是确保强一致性），leader才会将该日志放到状态机进行执行？对应code 段是在哪个文件呢？

**Describe the status of the current doc**
- Is there any doc yet?:
no.
- What other information should be added?
  - 比如加上如上的强一致性的日志同步过程，而不仅仅是snapshot。

**Comment by drmingdrmer** [comment]
Yes, openraft is a strictly implemented consensus algorithm and a log has to be replicated to a quorum of followers before committing and applying it.

When a leader writes a log entry, it queues it in `client_resp_channels`:
https://github.com/datafuselabs/openraft/blob/55217aa4786bee66b5cfac2662e1770434afb73f/openraft/src/core/raft_core.rs#L400-L428

When a log entry is successfully replicated to a quorum of followers, the leader applies it to state machine in:
https://github.com/datafuselabs/openraft/blob/55217aa4786bee66b5cfac2662e1770434afb73f/openraft/src/core/raft_core.rs#L689

Whether a log entry is committed is examined in:
https://github.com/datafuselabs/openraft/blob/ffcdd0ebba5f89d463ab40087306eb720b9f0cd7/openraft/src/engine/handler/replication_handler.rs#L166

**Comment by foonsun** [comment]
thanks for the reply.
