### ISSUE TITLE
Feature: Hide `tokio` dependencies behind an interface (trait)

### ISSUE THREAD

**Issue by schreter** [datafuselabs/openraft#741]
In out project, we are using a different async runtime than `tokio`. Especially, starting tasks is quite different. Therefore, we resorted to patching `openraft` to point to a small compat library which solves the problem.

However, this is suboptimal, since we have to regularly download openraft and store a copy in our repo, so we can modify its `Cargo.toml` to point `tokio` to the compatibility library. 

The idea would be to abstract the async runtime from openraft, since it currently uses only a minimal set of `tokio` primitives. This set of primitives can be hidden behind an `AsyncRuntime` trait, which would have a few associated types (again, pointing to relevant traits, e.g., for channels) and a few functions (like `spawn_task`). With that, it would be possible to specify the actual runtime externally and get rid of both the compat library and the need of patching. The default implementation would simply implement it by `tokio` primitives, of which many work in other async runtimes, too (from what `openraft` uses: specifically `Timeout` and spawning tasks doesn't, maybe some more).

Though our use case is quite special, `tokio` is not the only async library. Therefore, it would open the usage to the users of other async libraries as well.

**Comment by drmingdrmer** [comment]
It looks good to me.

Are you planning to submit a pull request for this task?
