### ISSUE TITLE
Append-entries support partial success return value

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#822]
An application can use this feature to send part of the log entries and return to the caller only the ones that were successfully replicated to a remote node.

### Why

If there are too many log entries and the `RPCOption.ttl` is not sufficient, an application can opt to only send a portion of the entries. Thus replication can still make progress.

### Changes

For better compatibility, simply add a new variant to the return value type of the append-entries RPC. Applications that do not need partial success can continue to function as is. However, for those applications that do use this feature, they can return `PartialSuccess`  instead of `Success` to provide Openraft with information on which log entries have been successfully replicated.

Here are the changes that are being suggested:

```diff
 pub enum AppendEntriesResponse<NID: NodeId> {
     Success,
+    PartialSuccess(Option<LogId<NID>>),
     Conflict,
     HigherVote(Vote<NID>),
 }
```

Requirement is discussed in:
- #787

**Comment by drmingdrmer** [comment]
@schreter

**Comment by schreter** [comment]
Thanks. Following my comment in the timeout PR, the timeout already on the first entry would be then represented as `PartialSuccess(None)`, right?

**Comment by drmingdrmer** [comment]
> Thanks. Following my comment in the timeout PR, the timeout already on the first entry would be then represented as `PartialSuccess(None)`, right?

`None` is acceptable.
It should be `AppendEntriesRequest.prev_log_id`, but Openraft should be able to tolerate it and correctly handle any value that is smaller or equal than the actually replicated log-id.

**Comment by drmingdrmer** [comment]
> Thanks. Following my comment in the timeout PR, the timeout already on the first entry would be then represented as `PartialSuccess(None)`, right?

@schreter 
`PartialSuccess(None)` should not be returned, if no progress is made, it should return an `RPCError`.

**Comment by schreter** [comment]
> PartialSuccess(None) should not be returned, if no progress is made, it should return an RPCError.

Ack, thanks.

**Comment by schreter** [comment]
> PartialSuccess(None) should not be returned, if no progress is made, it should return an RPCError.

Ack, thanks.
