### ISSUE TITLE
Possible issue with backoff when multiple nodes are unreachable

### ISSUE THREAD

**Issue by kevlu93** [datafuselabs/openraft#843]
After the new backoff feature was implemented with #779, we are trying to switch to use this new feature. It seems to work correctly when we kill a single voter in our three-node cluster. RPC calls to node 1 are sent based on the default backoff of 500ms. However, if I try to kill the remaining voter, after a single RPC calls, all of a sudden no more RPC calls are made. I've gone through the logs but I don't see any error suggesting why the node would stop making RPC calls. I have the logs still but it is a lot of entries, so I'm not sure what would be helpful to post, as I'm not sure what I should be looking for in terms of relevant warnings indicating why no more requests are being made.

**Comment by drmingdrmer** [comment]
You can not kill two nodes in a cluster of only three nodes. A majority requires at least two nodes.
The whole cluster will inevitably become unresponsive, whether or not using an "Unreachable" error and backoff.

The leader has received two `Unreachable` errors for all of the target node it replicates to. Thus by the design, the leader decide not to send anything out. This is as expected.

There should be several `warning` messages in the log, emitted by the two logging statements below. 

https://github.com/datafuselabs/openraft/blob/828ad87ca3f78fb02c9ec0b9c4d0768b1c59d281/openraft/src/replication/mod.rs#L255-L262

https://github.com/datafuselabs/openraft/blob/828ad87ca3f78fb02c9ec0b9c4d0768b1c59d281/openraft/src/replication/mod.rs#L475C1-L481

**Comment by drmingdrmer** [comment]
No such log message indicating that all nodes are unreachable.

And the critical state is not that all nodes are unreachable, but that a quorum of nodes are unreachable.

There is no such a log message because it may misleading: the leader can not be sure if it is a problem with the target node or a problem with the leader node.

To get a correct view of the cluster state, you must contact each node directly.
