### ISSUE TITLE
Cannot implement `RaftLogStorage` and `RaftStateMachine` in `main` codeline

### ISSUE THREAD

**Issue by schreter** [datafuselabs/openraft#858]
I'm trying to update to the newest openraft/main to get access to the newest development.

However, I'm unable to properly implement separate `RaftLogStorage` and `RaftStateMachine`, since both are "sealed". Using the `Adaptor` is contraproductive, since it's using an expensive async R/W lock to synchronize the two.

Since the `main` version is anyway a development state, shouldn't they be un-sealed there? Or at least provide a means (e.g., via a feature) to un-seal them, so I can adapt it properly?

Thanks in advance.

**Comment by schreter** [comment]
Ah, sorry for the noise, just found it, the feature `storage-v2`.

**Comment by tqwewe** [comment]
Definitely not noise, this saved me from scratching my head wondering why the trait is sealed..
