### ISSUE TITLE
Feature: Allow creating `!Send` storage, log and network components

### ISSUE THREAD

**Issue by schreter** [datafuselabs/openraft#862]
Currently, multiple global tasks are started for various work in `openraft`. These run potentially on different threads. This is fine for the generic case, but in our project, we use per-core local disk I/O and networking, etc., which requires the tasks to be `!Send`. The parallelism across cores is used to parallelize multiple consensus domains (i.e., multiple Rafts).

It would be nice to have a feature to turn off `Send` need on most traits and allow scheduler-local scheduling of Raft tasks. The idea is to use a special trait `OptionalSend` or so which would either require `Send` as supertrait or not based on the feature configuration.

To implement this, also task creation needs to be abstracted (but we have https://github.com/datafuselabs/openraft/issues/741 for that - this would handle starting the task as needed also based on the `OptionalSend` trait).

Opinions?

**Comment by drmingdrmer** [comment]
Interesting! Sounds a good idea to optimize heavily loaded concurrent system.

Another async-runtime that does not require a task to be `Send` is:
https://github.com/bytedance/monoio

Its primary goal is to improve the performance of applications that mainly processes network traffic.

**Comment by schreter** [comment]
> Interesting! Sounds a good idea to optimize heavily loaded concurrent system.

Yep, that's the intention :-).

Thanks for mentioning `monoio`, I didn't know it before. Maybe it'll save us some work on our runtime.
