### ISSUE TITLE
Manually impl `Clone` for `Raft` structure instead of using `#[derive(Clone)]`

### ISSUE THREAD

**Issue by xDarksome** [datafuselabs/openraft#870]
`#[derive(Clone)]`  puts `Clone` bounds on each type parameter. 
So, currently `Raft` only implements `Clone` if `Network` and `Storage` implement `Clone`.

However, `Raft` uses `Arc` under the hood for all of its dependencies, so we should be able to impl `Clone` regardless.

Maybe it's been done by design as a future proofing, but my speculation is that it's just a small oversight.

**Comment by drmingdrmer** [comment]
Nice point! Let me fix it!

Thank you!
