### ISSUE TITLE
raft.rs change_membership function call RaftMsg::ChangeMembership twice

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/openraft#88]
in raft.rs, change_membership function call RaftMsg::ChangeMembership twice with the same params (first to joint config, second to uniform config),this may make source readers confused.

How about add a param to indicate the action(joint,uniform) instead, this will make code more clearly.

**Comment by eliasyaoyc** [comment]
emmm, like this? 

```
pub enum ChangeMembershipStage{
    Joint,
    Uniform,
}

ChangeMembership {
   members: BTreeSet<NodeId>,
   blocking: bool,
   stage: ChangeMembershipStage,
   tx: RaftRespTx<ClientWriteResponse<R>, ClientWriteError>,
}
```

**Comment by lichuang** [comment]
> emmm, like this?
> 
> ```
> pub enum ChangeMembershipStage{
>     Joint,
>     Uniform,
> }
> 
> ChangeMembership {
>    members: BTreeSet<NodeId>,
>    blocking: bool,
>    stage: ChangeMembershipStage,
>    tx: RaftRespTx<ClientWriteResponse<R>, ClientWriteError>,
> }
> ```

yes, you got it!

**Comment by drmingdrmer** [comment]
Explained why the phase `Joint` or `Uniform` does not help:
https://github.com/datafuselabs/openraft/pull/89#discussion_r780387366
