### ISSUE TITLE
an issue from async-raft

### ISSUE THREAD

**Issue by pfwang80s** [datafuselabs/openraft#911]
how to repro:
1. start a single node 0 cluster
2. add non-vote node 1 to the cluster
3. add non-vote node 2 to the cluster
4. change membership {0, 1, 2}, now all these 3 nodes are in one cluster
5. kill node 0, the leader
6. a lot of "ERROR async_raft::replication: error sending AppendEntries RPC to target" errors are issued on node 1 or 2. 
7. connect to the new leader, change membership to {1, 2} to evict node 0, but 6 still continues

it seems there is a ReplicationStream to node 0 after step 7, it runs forever as RaftNetwork.append_entries to node 0 returns an network error, but target_state of it is not updated, check async-raft/src/replication/mod.rs:223.

**Does openraft have the same problem?**

thanks.

**Comment by drmingdrmer** [comment]
Yes Openraft has fixed this issue.

Every time replication changes, such as leader establish or quit, or membership change, the replication stream will be completely shutdown and restart again. All replication update is dealt with here:

https://github.com/datafuselabs/openraft/blob/d8e04177161f23b4b3f494031ad5875564b7edf6/openraft/src/core/raft_core.rs#L1632-L1644

**Comment by pfwang80s** [comment]
I do love OpenRaft now, thank you very much~

**Comment by pfwang80s** [comment]
issue closed.
