### ISSUE TITLE
Web APIs in example should follow RESTful style

### ISSUE THREAD

**Issue by pfwang80s** [datafuselabs/openraft#915]
e.g.: 
- /add_learner should be POST /learners
- /write should be POST or PUT /data/keys, actually, POST / PUT have different semantics, POST means new an item, PUT means modify
- /consistent_read should be GET /data/keys/\<key\>

**Comment by drmingdrmer** [comment]
Restful is more like a guideline, not a syntax rule.
what the style it is doesn't matter unless it is misleading.
I'd like it to be more explicit about what it's doing.

**Comment by drmingdrmer** [comment]
Close this issue. If you have any questions, please feel free to reopen it.
