### ISSUE TITLE
RaftMsg::ExternalRequest: should not rely on RaftLogStorage and RaftNetworkFactory

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/openraft#939]
`ExternalRequest` passes the implementation of `RaftLogStore` and
`RaftNetworkFactory` to a user defined `fn`.  This adds unnecessary
dependency(`N, LS`) to `RaftMsg`, `RaftInner` and `Raft`.

```rust
enum RaftMsg<C, N, LS> {
    ExternalRequest {
        req: Box< dyn FnOnce(&RaftState<...>, &mut LS, &mut N) >,
    },
}
```

---

Update: 2023-11-20:
~These types should be erased by replacing them with `&dny RaftLogStore` and
`&dyn RaftNetworkFactory`.~ 

Just remove `LS` and `N` from ExternalRequest.
Because `RaftLogStorage` will be moved out of `RaftCore` task, it's impossible to access `&RaftState` and `&LS` at the same time.

- #724
---

**Comment by schreter** [comment]
Thanks, as discussed on Discord, fine for me.

BTW, unless there are other users who feel otherwise, feel free to reduce the parameters to only `LS` or `SM` (probably `SM` makes more sense here, not sure). We can cope with either one in our project.

**Comment by drmingdrmer** [comment]
`dyn RaftLogStorage<C>` does not work, because it has an associated type `type LogReader: RaftLogReader<C>`.
To use it as trait object, the associated type must be specified. But as a parameter of a function signature, the associated type is unknown.
