### ISSUE TITLE
Add random number generation to `Runtime`

### ISSUE THREAD

**Issue by schreter** [datafuselabs/openraft#943]
Currently, `openraft` is using `rand` crate to generate random numbers and more concretely, the `thread_rng()`.

Unfortunately, this allocates at suboptimal times, which prevents us from hardening `openraft` in our project.

The thread-local random number generator query (and its type) should be added to the runtime interface and implemented by default using `rand` crate.

Alternatively, the random number generator should be created in the local state and not in TLS, which would work as well.

Background: TLS with destructors allocate an entry for running the destructor at thread exit in a vector. This allocation cannot be properly masked in our accounting and we get random extra allocation and/or deallocation accounted making memory leak tests fail.

**Comment by drmingdrmer** [comment]
`thread_rng()` is only used once in the codebase, when Engine is created. It is called only upon startup. Does it affect the performance? 

https://github.com/datafuselabs/openraft/blob/1e062d6d0b4b61f284d42936a56858bfccd839c0/openraft/src/engine/engine_config.rs#L45

**Comment by schreter** [comment]
> Does it affect the performance?

No, it's not about performance. It's about the ability to run malfunction and correctness tests of the code.

You don't have to do anything here, I'll take care of it. Just a heads-up.

BTW, shouldn't it use a newly-generated random number for each election?

**Comment by drmingdrmer** [comment]
OK I see.

> BTW, shouldn't it use a newly-generated random number for each election?

I'm not sure if it is necessary. At my POV, a random timeout for each node instead of for each round is good enough.
Do not know how to prove that 🤔

**Comment by schreter** [comment]
Completed by #995
