### ISSUE TITLE
Ditch `async_trait` in favor of the official `async_fn_in_trait` feature

### ISSUE THREAD

**Issue by wvwwvwwv** [datafuselabs/openraft#959]
Hello @drmingdrmer,

I guess you may already be aware of it, but the `async_fn_in_trait` feature has recently been stabilized in the nightly Rust channel and will be generally available in Rust 1.75.0. Currently, `openraft` heavily relies on the use of `async_trait` in order to provide asynchronous methods in traits, but obviously, `async_trait` has a negative effect on overall performance in many cases due to heap memory allocation.

So, I suggest that we try to get rid of `async_trait` incrementally.
- I didn't try it yet, but it would be possible since the current toolchain (nightly-10-17) already includes https://github.com/rust-lang/rust/pull/115822
- Unfortunately, a complete removal will not be easy due to many known issues with `async_fn_in_trait` and related language features, e.g., `Send` bound errors.
- Due to the notorious `Send` bound error, I think we should firstly focus on the `!OptionalSend` case.

**Comment by wvwwvwwv** [comment]
Update: just tried to remove `async_trait` by slightly modifying `macros/lib.rs` to _not emit_ `async_trait`, and it works pretty well.

**Comment by drmingdrmer** [comment]
Make sense.

Since you've already provided an entry in `macros/lib.rs` thus it would be easy to switch off `async_trait`, when rust `1.75.0` becomes stable :)

Before that, I think I should add a single threaded application example as a test for `singlethreaded` feature 🤔

**Comment by drmingdrmer** [comment]
@wvwwvwwv 
Is this issue fixed by?:
- #982

**Comment by wvwwvwwv** [comment]
Nope, we can close this issue for now since we cannot currently get rid of every async_trait usage due to some limitations in the Rust compiler.
