### ISSUE TITLE
Refactor: Move `client_resp_channels` from `LeaderData` to new `tx_...`-field in `RaftCore`

### ISSUE THREAD

**Issue by tvsfx** [datafuselabs/openraft#963]
Currently, the `QuitLeader` command makes the `RaftCore` [drop the node's client response channels](https://github.com/datafuselabs/openraft/blob/b84e4145fc96ca6c7f43c1ecd2f3d2c6bea4d2db/openraft/src/core/raft_core.rs#L1535).
However, even when the node becomes a follower, it can still keep its existing response channels around, and reply to them when it applies the corresponding entries, even though it is no longer a leader at that time. This is correct, since no uncommitted entries will ever be applied. This simplifies the `QuitLeader` logic.
If `client_resp_channels` is moved out of the `LeaderData`, this becomes possible.
The check to see whether we are a leader at entry apply-time would then also disappear from [here](https://github.com/datafuselabs/openraft/blob/b84e4145fc96ca6c7f43c1ecd2f3d2c6bea4d2db/openraft/src/core/raft_core.rs#L706).

As an aside, having the list of client response channels in each node would also be convenient for follower reads or read indexes in the future.

**Comment by drmingdrmer** [comment]
Nice catch! My hero!
