### ISSUE TITLE
about single node

### ISSUE THREAD

**Issue by web3creator** [datafuselabs/openraft#966]
If I start a node and set it as leader, will there be any problems if the node keeps running?

**Comment by drmingdrmer** [comment]
No problem at all.

It's quite typical to initiate a cluster with a single node for testing purposes.

Are there any specific concerns you have in mind?

**Comment by web3creator** [comment]
I have a cluster and need to start many  work node
1: Add these nodes to the cluster as learners
2: Each of these work nodes starts the raft service independently.Synchronize data via rpc,These work nodes will execute raft::new()raft::initialize(self.node.id),Will this work well even if it is shut down and restarted?

**Comment by drmingdrmer** [comment]
Starting a single node and adding the others as learners would be better.

Restart should not affect anything about persisted data:
If you correctly implement the storage layer, the `RaftStorage`, by persisting data before returning in every method, the data should remain intact during shutdown and restart processes. This ensures that no data is lost or damaged in such scenarios.

**Comment by web3creator** [comment]
@drmingdrmer If 200 learner nodes are added to a cluster, will there be any change in performance compared to no increase?

**Comment by drmingdrmer** [comment]
In that case, the impact on performance will be significant.

All replications are transmitted from the Leader to Followers/Learners, placing the Leader under a comparatively high workload.
