### ISSUE TITLE
Cluster Bootstrap and Node Initialization Sequence

### ISSUE THREAD

**Issue by diptanu** [datafuselabs/openraft#970]
I would love some explanation about cluster bootstrap and initialization process under the following scenarios -

1. When cluster is being bootstrapped by starting N number of nodes around the same time with the same configuration(list of nodes).
2. Node is being restarted which were part of a cluster. 

My understanding is that -
1. a Node need to initialized with only itself. 
2. Add the other nodes as learners
3. Change the membership to include all the nodes 

Every node needs to be running the same sequence. Is that correct?

**Comment by drmingdrmer** [comment]
In this PR I added some instructions for initializing a cluster:

- #971

Did that help clear up your confusion?

**Comment by drmingdrmer** [comment]
FYI:
https://docs.rs/openraft/latest/openraft/docs/faq/index.html

**Comment by diptanu** [comment]
@drmingdrmer Thanks for the docs! I am closing the issue. This is super helpful :)
