### ISSUE TITLE
Observe state changes in a Raft node 

### ISSUE THREAD

**Issue by diptanu** [datafuselabs/openraft#984]
HI @drmingdrmer, what's the best way to get notified when the raft node's server state changes? I want the leader node to run some tasks, and stop them when it loses leadership. Is there a good api to get a stream of state changes? I saw that there is a wait method which waits for a specific state, but in that case if I am waiting only for leader I am wondering how I can know that the leadership is lost after a node becomes a leader prior to that.

**Comment by drmingdrmer** [comment]
To monitor the state of a Raft node in OpenRaft, it's recommended to subscribe to updates in the `RaftMetrics`. The following code snippet provides an example of how to wait for changes in `RaftMetrics` until a leader is elected:

https://github.com/drmingdrmer/databend/blob/313b40ed3ff1cfe001bc6e2f806773d9001861d0/src/meta/service/src/meta_service/meta_node.rs#L1149-L1173


```rust
        let mut rx = self.raft.metrics();

        loop {
            if let Some(l) = rx.borrow().current_leader {
                return Ok(Some(l));
            }

            rx.changed().await?;
        }

```

This approach allows you to react to changes in the cluster's leadership efficiently. For more detailed information, refer to the specific section of the code in the [`RaftMetrics::state`](https://github.com/datafuselabs/openraft/blob/147de251551c1ed364bd60bbe57047393e1d625e/openraft/src/metrics/raft_metrics.rs#L35).

**Comment by diptanu** [comment]
@drmingdrmer I tried this out, looks like the receiver of raft metrics unblocks every few millisecond. Is there any way to subscribe to only leadership change notifications?

**Comment by drmingdrmer** [comment]
You need to verify whether `RaftMetrics::state` has changed for your purpose. There is an active issue that involves dividing `RaftMetrics` into two separate entities. Despite this, you must still check whether the specific field of interest to you has been changed.

- #985

**Comment by diptanu** [comment]
@drmingdrmer Understood! I have an implementation here - https://github.com/diptanu/indexify/pull/221 would appreciate if you can take a look and provide some feedback :)

**Comment by drmingdrmer** [comment]
> @drmingdrmer Understood! I have an implementation here - [diptanu/indexify#221](https://github.com/diptanu/indexify/pull/221) would appreciate if you can take a look and provide some feedback :)

Of course. I've added some comments on your pull request.
